/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Beskrivelse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Beskrivelse {

  @JsonProperty("type")

  private String type = null;

  @JsonProperty("beskrivelse")

  private String beskrivelse = null;
  public Beskrivelse type(String type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }
  public Beskrivelse beskrivelse(String beskrivelse) {
    this.beskrivelse = beskrivelse;
    return this;
  }

  

  /**
  * Get beskrivelse
  * @return beskrivelse
  **/
  @Schema(description = "")
  public String getBeskrivelse() {
    return beskrivelse;
  }
  public void setBeskrivelse(String beskrivelse) {
    this.beskrivelse = beskrivelse;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Beskrivelse beskrivelse = (Beskrivelse) o;
    return Objects.equals(this.type, beskrivelse.type) &&
        Objects.equals(this.beskrivelse, beskrivelse.beskrivelse);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(type, beskrivelse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Beskrivelse {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    beskrivelse: ").append(toIndentedString(beskrivelse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
