/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.SprakFelter;

/**
 * BIBSYSBestStedInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class BIBSYSBestStedInfo {

  @JsonProperty("kode")

  private String kode = null;

  @JsonProperty("stednavn")

  private String stednavn = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("aktiv")

  private Boolean aktiv = null;
  public BIBSYSBestStedInfo kode(String kode) {
    this.kode = kode;
    return this;
  }

  

  /**
  * Get kode
  * @return kode
  **/
  @Schema(description = "")
  public String getKode() {
    return kode;
  }
  public void setKode(String kode) {
    this.kode = kode;
  }
  public BIBSYSBestStedInfo stednavn(String stednavn) {
    this.stednavn = stednavn;
    return this;
  }

  

  /**
  * Get stednavn
  * @return stednavn
  **/
  @Schema(description = "")
  public String getStednavn() {
    return stednavn;
  }
  public void setStednavn(String stednavn) {
    this.stednavn = stednavn;
  }
  public BIBSYSBestStedInfo navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public BIBSYSBestStedInfo aktiv(Boolean aktiv) {
    this.aktiv = aktiv;
    return this;
  }

  

  /**
  * Get aktiv
  * @return aktiv
  **/
  @Schema(description = "")
  public Boolean isAktiv() {
    return aktiv;
  }
  public void setAktiv(Boolean aktiv) {
    this.aktiv = aktiv;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BIBSYSBestStedInfo biBSYSBestStedInfo = (BIBSYSBestStedInfo) o;
    return Objects.equals(this.kode, biBSYSBestStedInfo.kode) &&
        Objects.equals(this.stednavn, biBSYSBestStedInfo.stednavn) &&
        Objects.equals(this.navn, biBSYSBestStedInfo.navn) &&
        Objects.equals(this.aktiv, biBSYSBestStedInfo.aktiv);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(kode, stednavn, navn, aktiv);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BIBSYSBestStedInfo {\n");
    
    sb.append("    kode: ").append(toIndentedString(kode)).append("\n");
    sb.append("    stednavn: ").append(toIndentedString(stednavn)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
