/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.CampusId;
import no.bibsys.fs.model.Id2;
import no.bibsys.fs.model.KommuneInfo;
import no.bibsys.fs.model.SprakFelter;

/**
 * Campus
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Campus {

  @JsonProperty("id")

  private CampusId id = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("land")

  private Id2 land = null;

  @JsonProperty("kommune")

  private KommuneInfo kommune = null;

  @JsonProperty("organisasjonsnummer")

  private Integer organisasjonsnummer = null;

  @JsonProperty("default")

  private Boolean _default = null;
  public Campus id(CampusId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public CampusId getId() {
    return id;
  }
  public void setId(CampusId id) {
    this.id = id;
  }
  public Campus navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public Campus land(Id2 land) {
    this.land = land;
    return this;
  }

  

  /**
  * Get land
  * @return land
  **/
  @Schema(description = "")
  public Id2 getLand() {
    return land;
  }
  public void setLand(Id2 land) {
    this.land = land;
  }
  public Campus kommune(KommuneInfo kommune) {
    this.kommune = kommune;
    return this;
  }

  

  /**
  * Get kommune
  * @return kommune
  **/
  @Schema(description = "")
  public KommuneInfo getKommune() {
    return kommune;
  }
  public void setKommune(KommuneInfo kommune) {
    this.kommune = kommune;
  }
  public Campus organisasjonsnummer(Integer organisasjonsnummer) {
    this.organisasjonsnummer = organisasjonsnummer;
    return this;
  }

  

  /**
  * Get organisasjonsnummer
  * @return organisasjonsnummer
  **/
  @Schema(description = "")
  public Integer getOrganisasjonsnummer() {
    return organisasjonsnummer;
  }
  public void setOrganisasjonsnummer(Integer organisasjonsnummer) {
    this.organisasjonsnummer = organisasjonsnummer;
  }
  public Campus _default(Boolean _default) {
    this._default = _default;
    return this;
  }

  

  /**
  * Get _default
  * @return _default
  **/
  @Schema(description = "")
  public Boolean isDefault() {
    return _default;
  }
  public void setDefault(Boolean _default) {
    this._default = _default;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Campus campus = (Campus) o;
    return Objects.equals(this.id, campus.id) &&
        Objects.equals(this.navn, campus.navn) &&
        Objects.equals(this.land, campus.land) &&
        Objects.equals(this.kommune, campus.kommune) &&
        Objects.equals(this.organisasjonsnummer, campus.organisasjonsnummer) &&
        Objects.equals(this._default, campus._default);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, navn, land, kommune, organisasjonsnummer, _default);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Campus {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    land: ").append(toIndentedString(land)).append("\n");
    sb.append("    kommune: ").append(toIndentedString(kommune)).append("\n");
    sb.append("    organisasjonsnummer: ").append(toIndentedString(organisasjonsnummer)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
