/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.EmneId;
import no.bibsys.fs.model.Id2;
import no.bibsys.fs.model.Links;
import no.bibsys.fs.model.SprakFelter;

/**
 * Emne
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Emne {

  @JsonProperty("id")

  private EmneId id = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("studieniva")

  private Id2 studieniva = null;

  @JsonProperty("organisasjonsenheter")

  private Links organisasjonsenheter = null;

  @JsonProperty("hovedoppgave")

  private Boolean hovedoppgave = null;
  public Emne id(EmneId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public EmneId getId() {
    return id;
  }
  public void setId(EmneId id) {
    this.id = id;
  }
  public Emne navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public Emne studieniva(Id2 studieniva) {
    this.studieniva = studieniva;
    return this;
  }

  

  /**
  * Get studieniva
  * @return studieniva
  **/
  @Schema(description = "")
  public Id2 getStudieniva() {
    return studieniva;
  }
  public void setStudieniva(Id2 studieniva) {
    this.studieniva = studieniva;
  }
  public Emne organisasjonsenheter(Links organisasjonsenheter) {
    this.organisasjonsenheter = organisasjonsenheter;
    return this;
  }

  

  /**
  * Get organisasjonsenheter
  * @return organisasjonsenheter
  **/
  @Schema(description = "")
  public Links getOrganisasjonsenheter() {
    return organisasjonsenheter;
  }
  public void setOrganisasjonsenheter(Links organisasjonsenheter) {
    this.organisasjonsenheter = organisasjonsenheter;
  }
  public Emne hovedoppgave(Boolean hovedoppgave) {
    this.hovedoppgave = hovedoppgave;
    return this;
  }

  

  /**
  * Get hovedoppgave
  * @return hovedoppgave
  **/
  @Schema(description = "")
  public Boolean isHovedoppgave() {
    return hovedoppgave;
  }
  public void setHovedoppgave(Boolean hovedoppgave) {
    this.hovedoppgave = hovedoppgave;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Emne emne = (Emne) o;
    return Objects.equals(this.id, emne.id) &&
        Objects.equals(this.navn, emne.navn) &&
        Objects.equals(this.studieniva, emne.studieniva) &&
        Objects.equals(this.organisasjonsenheter, emne.organisasjonsenheter) &&
        Objects.equals(this.hovedoppgave, emne.hovedoppgave);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, navn, studieniva, organisasjonsenheter, hovedoppgave);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Emne {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    studieniva: ").append(toIndentedString(studieniva)).append("\n");
    sb.append("    organisasjonsenheter: ").append(toIndentedString(organisasjonsenheter)).append("\n");
    sb.append("    hovedoppgave: ").append(toIndentedString(hovedoppgave)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
