/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ErrorResponseErrors
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class ErrorResponseErrors {

  @JsonProperty("code")

  private Integer code = null;

  @JsonProperty("message")

  private String message = null;

  @JsonProperty("errorCorrection")

  private String errorCorrection = null;
  public ErrorResponseErrors code(Integer code) {
    this.code = code;
    return this;
  }

  

  /**
  * Kode for forskjellige typer feil
  * @return code
  **/
  @Schema(description = "Kode for forskjellige typer feil")
  public Integer getCode() {
    return code;
  }
  public void setCode(Integer code) {
    this.code = code;
  }
  public ErrorResponseErrors message(String message) {
    this.message = message;
    return this;
  }

  

  /**
  * Beskrivelse av feil
  * @return message
  **/
  @Schema(description = "Beskrivelse av feil")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }
  public ErrorResponseErrors errorCorrection(String errorCorrection) {
    this.errorCorrection = errorCorrection;
    return this;
  }

  

  /**
  * Instruksjoner om hvordan du kan løse feil
  * @return errorCorrection
  **/
  @Schema(description = "Instruksjoner om hvordan du kan løse feil")
  public String getErrorCorrection() {
    return errorCorrection;
  }
  public void setErrorCorrection(String errorCorrection) {
    this.errorCorrection = errorCorrection;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponseErrors errorResponseErrors = (ErrorResponseErrors) o;
    return Objects.equals(this.code, errorResponseErrors.code) &&
        Objects.equals(this.message, errorResponseErrors.message) &&
        Objects.equals(this.errorCorrection, errorResponseErrors.errorCorrection);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(code, message, errorCorrection);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponseErrors {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    errorCorrection: ").append(toIndentedString(errorCorrection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
