/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import no.bibsys.fs.model.ErrorResponseErrors;
import org.threeten.bp.OffsetDateTime;

/**
 * ErrorResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class ErrorResponse {

  @JsonProperty("status")

  private Integer status = null;

  @JsonProperty("errors")

  private List<ErrorResponseErrors> errors = null;

  @JsonProperty("created")

  private OffsetDateTime created = null;
  public ErrorResponse status(Integer status) {
    this.status = status;
    return this;
  }

  

  /**
  * http error status
  * @return status
  **/
  @Schema(description = "http error status")
  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }
  public ErrorResponse errors(List<ErrorResponseErrors> errors) {
    this.errors = errors;
    return this;
  }

  public ErrorResponse addErrorsItem(ErrorResponseErrors errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<ErrorResponseErrors>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
  * Get errors
  * @return errors
  **/
  @Schema(description = "")
  public List<ErrorResponseErrors> getErrors() {
    return errors;
  }
  public void setErrors(List<ErrorResponseErrors> errors) {
    this.errors = errors;
  }
  public ErrorResponse created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

  

  /**
  * Klolleslett når en feil oppsto
  * @return created
  **/
  @Schema(description = "Klolleslett når en feil oppsto")
  public OffsetDateTime getCreated() {
    return created;
  }
  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponse errorResponse = (ErrorResponse) o;
    return Objects.equals(this.status, errorResponse.status) &&
        Objects.equals(this.errors, errorResponse.errors) &&
        Objects.equals(this.created, errorResponse.created);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(status, errors, created);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
