/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.Id2;

/**
 * EvuKursDeltakelseId
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class EvuKursDeltakelseId {

  @JsonProperty("href")

  private String href = null;
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    EMPTY("");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }
  @JsonProperty("type")

  private TypeEnum type = null;

  @JsonProperty("deltaker")

  private Id2 deltaker = null;

  @JsonProperty("evuKurs")

  private Id2 evuKurs = null;
  public EvuKursDeltakelseId href(String href) {
    this.href = href;
    return this;
  }

  

  /**
  * Get href
  * @return href
  **/
  @Schema(example = "https://server/evukursdeltakelse/id", description = "")
  public String getHref() {
    return href;
  }
  public void setHref(String href) {
    this.href = href;
  }
  public EvuKursDeltakelseId type(TypeEnum type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }
  public void setType(TypeEnum type) {
    this.type = type;
  }
  public EvuKursDeltakelseId deltaker(Id2 deltaker) {
    this.deltaker = deltaker;
    return this;
  }

  

  /**
  * Get deltaker
  * @return deltaker
  **/
  @Schema(description = "")
  public Id2 getDeltaker() {
    return deltaker;
  }
  public void setDeltaker(Id2 deltaker) {
    this.deltaker = deltaker;
  }
  public EvuKursDeltakelseId evuKurs(Id2 evuKurs) {
    this.evuKurs = evuKurs;
    return this;
  }

  

  /**
  * Get evuKurs
  * @return evuKurs
  **/
  @Schema(description = "")
  public Id2 getEvuKurs() {
    return evuKurs;
  }
  public void setEvuKurs(Id2 evuKurs) {
    this.evuKurs = evuKurs;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvuKursDeltakelseId evuKursDeltakelseId = (EvuKursDeltakelseId) o;
    return Objects.equals(this.href, evuKursDeltakelseId.href) &&
        Objects.equals(this.type, evuKursDeltakelseId.type) &&
        Objects.equals(this.deltaker, evuKursDeltakelseId.deltaker) &&
        Objects.equals(this.evuKurs, evuKursDeltakelseId.evuKurs);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(href, type, deltaker, evuKurs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvuKursDeltakelseId {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    deltaker: ").append(toIndentedString(deltaker)).append("\n");
    sb.append("    evuKurs: ").append(toIndentedString(evuKurs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
