/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.FagId;
import no.bibsys.fs.model.ISCEDInfo;
import no.bibsys.fs.model.Links;
import no.bibsys.fs.model.NSDFagTypeInfo;
import no.bibsys.fs.model.SprakFelter;
import no.bibsys.fs.model.SubjectArea;
import no.bibsys.fs.model.VitenskapsDisiplinInfo;

/**
 * Fag
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Fag {

  @JsonProperty("id")

  private FagId id = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("organisasjonsenheter")

  private Links organisasjonsenheter = null;

  @JsonProperty("subjectArea")

  private SubjectArea subjectArea = null;

  @JsonProperty("isced")

  private ISCEDInfo isced = null;

  @JsonProperty("nsdFagType")

  private NSDFagTypeInfo nsdFagType = null;

  @JsonProperty("vitenskapsdisiplin")

  private VitenskapsDisiplinInfo vitenskapsdisiplin = null;

  @JsonProperty("prioritet")

  private Integer prioritet = null;

  @JsonProperty("aktiv")

  private Boolean aktiv = null;

  @JsonProperty("felles")

  private Boolean felles = null;
  public Fag id(FagId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public FagId getId() {
    return id;
  }
  public void setId(FagId id) {
    this.id = id;
  }
  public Fag navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public Fag organisasjonsenheter(Links organisasjonsenheter) {
    this.organisasjonsenheter = organisasjonsenheter;
    return this;
  }

  

  /**
  * Get organisasjonsenheter
  * @return organisasjonsenheter
  **/
  @Schema(description = "")
  public Links getOrganisasjonsenheter() {
    return organisasjonsenheter;
  }
  public void setOrganisasjonsenheter(Links organisasjonsenheter) {
    this.organisasjonsenheter = organisasjonsenheter;
  }
  public Fag subjectArea(SubjectArea subjectArea) {
    this.subjectArea = subjectArea;
    return this;
  }

  

  /**
  * Get subjectArea
  * @return subjectArea
  **/
  @Schema(description = "")
  public SubjectArea getSubjectArea() {
    return subjectArea;
  }
  public void setSubjectArea(SubjectArea subjectArea) {
    this.subjectArea = subjectArea;
  }
  public Fag isced(ISCEDInfo isced) {
    this.isced = isced;
    return this;
  }

  

  /**
  * Get isced
  * @return isced
  **/
  @Schema(description = "")
  public ISCEDInfo getIsced() {
    return isced;
  }
  public void setIsced(ISCEDInfo isced) {
    this.isced = isced;
  }
  public Fag nsdFagType(NSDFagTypeInfo nsdFagType) {
    this.nsdFagType = nsdFagType;
    return this;
  }

  

  /**
  * Get nsdFagType
  * @return nsdFagType
  **/
  @Schema(description = "")
  public NSDFagTypeInfo getNsdFagType() {
    return nsdFagType;
  }
  public void setNsdFagType(NSDFagTypeInfo nsdFagType) {
    this.nsdFagType = nsdFagType;
  }
  public Fag vitenskapsdisiplin(VitenskapsDisiplinInfo vitenskapsdisiplin) {
    this.vitenskapsdisiplin = vitenskapsdisiplin;
    return this;
  }

  

  /**
  * Get vitenskapsdisiplin
  * @return vitenskapsdisiplin
  **/
  @Schema(description = "")
  public VitenskapsDisiplinInfo getVitenskapsdisiplin() {
    return vitenskapsdisiplin;
  }
  public void setVitenskapsdisiplin(VitenskapsDisiplinInfo vitenskapsdisiplin) {
    this.vitenskapsdisiplin = vitenskapsdisiplin;
  }
  public Fag prioritet(Integer prioritet) {
    this.prioritet = prioritet;
    return this;
  }

  

  /**
  * Get prioritet
  * @return prioritet
  **/
  @Schema(description = "")
  public Integer getPrioritet() {
    return prioritet;
  }
  public void setPrioritet(Integer prioritet) {
    this.prioritet = prioritet;
  }
  public Fag aktiv(Boolean aktiv) {
    this.aktiv = aktiv;
    return this;
  }

  

  /**
  * Get aktiv
  * @return aktiv
  **/
  @Schema(description = "")
  public Boolean isAktiv() {
    return aktiv;
  }
  public void setAktiv(Boolean aktiv) {
    this.aktiv = aktiv;
  }
  public Fag felles(Boolean felles) {
    this.felles = felles;
    return this;
  }

  

  /**
  * Get felles
  * @return felles
  **/
  @Schema(description = "")
  public Boolean isFelles() {
    return felles;
  }
  public void setFelles(Boolean felles) {
    this.felles = felles;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fag fag = (Fag) o;
    return Objects.equals(this.id, fag.id) &&
        Objects.equals(this.navn, fag.navn) &&
        Objects.equals(this.organisasjonsenheter, fag.organisasjonsenheter) &&
        Objects.equals(this.subjectArea, fag.subjectArea) &&
        Objects.equals(this.isced, fag.isced) &&
        Objects.equals(this.nsdFagType, fag.nsdFagType) &&
        Objects.equals(this.vitenskapsdisiplin, fag.vitenskapsdisiplin) &&
        Objects.equals(this.prioritet, fag.prioritet) &&
        Objects.equals(this.aktiv, fag.aktiv) &&
        Objects.equals(this.felles, fag.felles);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, navn, organisasjonsenheter, subjectArea, isced, nsdFagType, vitenskapsdisiplin, prioritet, aktiv, felles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fag {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    organisasjonsenheter: ").append(toIndentedString(organisasjonsenheter)).append("\n");
    sb.append("    subjectArea: ").append(toIndentedString(subjectArea)).append("\n");
    sb.append("    isced: ").append(toIndentedString(isced)).append("\n");
    sb.append("    nsdFagType: ").append(toIndentedString(nsdFagType)).append("\n");
    sb.append("    vitenskapsdisiplin: ").append(toIndentedString(vitenskapsdisiplin)).append("\n");
    sb.append("    prioritet: ").append(toIndentedString(prioritet)).append("\n");
    sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
    sb.append("    felles: ").append(toIndentedString(felles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
