/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.Id;

/**
 * FagpersonInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class FagpersonInfo {

  @JsonProperty("aktiv")

  private Boolean aktiv = null;

  @JsonProperty("organisasjonsenhet")

  private Id organisasjonsenhet = null;
  public FagpersonInfo aktiv(Boolean aktiv) {
    this.aktiv = aktiv;
    return this;
  }

  

  /**
  * Get aktiv
  * @return aktiv
  **/
  @Schema(description = "")
  public Boolean isAktiv() {
    return aktiv;
  }
  public void setAktiv(Boolean aktiv) {
    this.aktiv = aktiv;
  }
  public FagpersonInfo organisasjonsenhet(Id organisasjonsenhet) {
    this.organisasjonsenhet = organisasjonsenhet;
    return this;
  }

  

  /**
  * Get organisasjonsenhet
  * @return organisasjonsenhet
  **/
  @Schema(description = "")
  public Id getOrganisasjonsenhet() {
    return organisasjonsenhet;
  }
  public void setOrganisasjonsenhet(Id organisasjonsenhet) {
    this.organisasjonsenhet = organisasjonsenhet;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FagpersonInfo fagpersonInfo = (FagpersonInfo) o;
    return Objects.equals(this.aktiv, fagpersonInfo.aktiv) &&
        Objects.equals(this.organisasjonsenhet, fagpersonInfo.organisasjonsenhet);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(aktiv, organisasjonsenhet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FagpersonInfo {\n");
    
    sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
    sb.append("    organisasjonsenhet: ").append(toIndentedString(organisasjonsenhet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
