/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.FnrEndringId;
import no.bibsys.fs.model.Fodselsnummer;
import no.bibsys.fs.model.Id2;
import org.threeten.bp.LocalDate;

/**
 * FnrEndring
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class FnrEndring {

  @JsonProperty("id")

  private FnrEndringId id = null;

  @JsonProperty("datoForetatt")

  private LocalDate datoForetatt = null;

  @JsonProperty("naverendeFodselsnummer")

  private Fodselsnummer naverendeFodselsnummer = null;

  @JsonProperty("tidligereFodselsnummer")

  private Fodselsnummer tidligereFodselsnummer = null;

  @JsonProperty("nesteFodselsnummer")

  private Fodselsnummer nesteFodselsnummer = null;

  @JsonProperty("semester")

  private Id2 semester = null;

  @JsonProperty("sammenslatt")

  private Boolean sammenslatt = null;

  @JsonProperty("behandletAvSamordnaOpptak")

  private Boolean behandletAvSamordnaOpptak = null;

  @JsonProperty("datoMeldtSamordnaOpptak")

  private LocalDate datoMeldtSamordnaOpptak = null;

  @JsonProperty("bestillingsIdSamordnaOpptak")

  private Integer bestillingsIdSamordnaOpptak = null;

  @JsonProperty("grunnlagsmerknad")

  private String grunnlagsmerknad = null;
  public FnrEndring id(FnrEndringId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public FnrEndringId getId() {
    return id;
  }
  public void setId(FnrEndringId id) {
    this.id = id;
  }
  public FnrEndring datoForetatt(LocalDate datoForetatt) {
    this.datoForetatt = datoForetatt;
    return this;
  }

  

  /**
  * Get datoForetatt
  * @return datoForetatt
  **/
  @Schema(description = "")
  public LocalDate getDatoForetatt() {
    return datoForetatt;
  }
  public void setDatoForetatt(LocalDate datoForetatt) {
    this.datoForetatt = datoForetatt;
  }
  public FnrEndring naverendeFodselsnummer(Fodselsnummer naverendeFodselsnummer) {
    this.naverendeFodselsnummer = naverendeFodselsnummer;
    return this;
  }

  

  /**
  * Get naverendeFodselsnummer
  * @return naverendeFodselsnummer
  **/
  @Schema(description = "")
  public Fodselsnummer getNaverendeFodselsnummer() {
    return naverendeFodselsnummer;
  }
  public void setNaverendeFodselsnummer(Fodselsnummer naverendeFodselsnummer) {
    this.naverendeFodselsnummer = naverendeFodselsnummer;
  }
  public FnrEndring tidligereFodselsnummer(Fodselsnummer tidligereFodselsnummer) {
    this.tidligereFodselsnummer = tidligereFodselsnummer;
    return this;
  }

  

  /**
  * Get tidligereFodselsnummer
  * @return tidligereFodselsnummer
  **/
  @Schema(description = "")
  public Fodselsnummer getTidligereFodselsnummer() {
    return tidligereFodselsnummer;
  }
  public void setTidligereFodselsnummer(Fodselsnummer tidligereFodselsnummer) {
    this.tidligereFodselsnummer = tidligereFodselsnummer;
  }
  public FnrEndring nesteFodselsnummer(Fodselsnummer nesteFodselsnummer) {
    this.nesteFodselsnummer = nesteFodselsnummer;
    return this;
  }

  

  /**
  * Get nesteFodselsnummer
  * @return nesteFodselsnummer
  **/
  @Schema(description = "")
  public Fodselsnummer getNesteFodselsnummer() {
    return nesteFodselsnummer;
  }
  public void setNesteFodselsnummer(Fodselsnummer nesteFodselsnummer) {
    this.nesteFodselsnummer = nesteFodselsnummer;
  }
  public FnrEndring semester(Id2 semester) {
    this.semester = semester;
    return this;
  }

  

  /**
  * Get semester
  * @return semester
  **/
  @Schema(description = "")
  public Id2 getSemester() {
    return semester;
  }
  public void setSemester(Id2 semester) {
    this.semester = semester;
  }
  public FnrEndring sammenslatt(Boolean sammenslatt) {
    this.sammenslatt = sammenslatt;
    return this;
  }

  

  /**
  * Get sammenslatt
  * @return sammenslatt
  **/
  @Schema(description = "")
  public Boolean isSammenslatt() {
    return sammenslatt;
  }
  public void setSammenslatt(Boolean sammenslatt) {
    this.sammenslatt = sammenslatt;
  }
  public FnrEndring behandletAvSamordnaOpptak(Boolean behandletAvSamordnaOpptak) {
    this.behandletAvSamordnaOpptak = behandletAvSamordnaOpptak;
    return this;
  }

  

  /**
  * Get behandletAvSamordnaOpptak
  * @return behandletAvSamordnaOpptak
  **/
  @Schema(description = "")
  public Boolean isBehandletAvSamordnaOpptak() {
    return behandletAvSamordnaOpptak;
  }
  public void setBehandletAvSamordnaOpptak(Boolean behandletAvSamordnaOpptak) {
    this.behandletAvSamordnaOpptak = behandletAvSamordnaOpptak;
  }
  public FnrEndring datoMeldtSamordnaOpptak(LocalDate datoMeldtSamordnaOpptak) {
    this.datoMeldtSamordnaOpptak = datoMeldtSamordnaOpptak;
    return this;
  }

  

  /**
  * Get datoMeldtSamordnaOpptak
  * @return datoMeldtSamordnaOpptak
  **/
  @Schema(description = "")
  public LocalDate getDatoMeldtSamordnaOpptak() {
    return datoMeldtSamordnaOpptak;
  }
  public void setDatoMeldtSamordnaOpptak(LocalDate datoMeldtSamordnaOpptak) {
    this.datoMeldtSamordnaOpptak = datoMeldtSamordnaOpptak;
  }
  public FnrEndring bestillingsIdSamordnaOpptak(Integer bestillingsIdSamordnaOpptak) {
    this.bestillingsIdSamordnaOpptak = bestillingsIdSamordnaOpptak;
    return this;
  }

  

  /**
  * Get bestillingsIdSamordnaOpptak
  * @return bestillingsIdSamordnaOpptak
  **/
  @Schema(description = "")
  public Integer getBestillingsIdSamordnaOpptak() {
    return bestillingsIdSamordnaOpptak;
  }
  public void setBestillingsIdSamordnaOpptak(Integer bestillingsIdSamordnaOpptak) {
    this.bestillingsIdSamordnaOpptak = bestillingsIdSamordnaOpptak;
  }
  public FnrEndring grunnlagsmerknad(String grunnlagsmerknad) {
    this.grunnlagsmerknad = grunnlagsmerknad;
    return this;
  }

  

  /**
  * Get grunnlagsmerknad
  * @return grunnlagsmerknad
  **/
  @Schema(description = "")
  public String getGrunnlagsmerknad() {
    return grunnlagsmerknad;
  }
  public void setGrunnlagsmerknad(String grunnlagsmerknad) {
    this.grunnlagsmerknad = grunnlagsmerknad;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FnrEndring fnrEndring = (FnrEndring) o;
    return Objects.equals(this.id, fnrEndring.id) &&
        Objects.equals(this.datoForetatt, fnrEndring.datoForetatt) &&
        Objects.equals(this.naverendeFodselsnummer, fnrEndring.naverendeFodselsnummer) &&
        Objects.equals(this.tidligereFodselsnummer, fnrEndring.tidligereFodselsnummer) &&
        Objects.equals(this.nesteFodselsnummer, fnrEndring.nesteFodselsnummer) &&
        Objects.equals(this.semester, fnrEndring.semester) &&
        Objects.equals(this.sammenslatt, fnrEndring.sammenslatt) &&
        Objects.equals(this.behandletAvSamordnaOpptak, fnrEndring.behandletAvSamordnaOpptak) &&
        Objects.equals(this.datoMeldtSamordnaOpptak, fnrEndring.datoMeldtSamordnaOpptak) &&
        Objects.equals(this.bestillingsIdSamordnaOpptak, fnrEndring.bestillingsIdSamordnaOpptak) &&
        Objects.equals(this.grunnlagsmerknad, fnrEndring.grunnlagsmerknad);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, datoForetatt, naverendeFodselsnummer, tidligereFodselsnummer, nesteFodselsnummer, semester, sammenslatt, behandletAvSamordnaOpptak, datoMeldtSamordnaOpptak, bestillingsIdSamordnaOpptak, grunnlagsmerknad);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FnrEndring {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    datoForetatt: ").append(toIndentedString(datoForetatt)).append("\n");
    sb.append("    naverendeFodselsnummer: ").append(toIndentedString(naverendeFodselsnummer)).append("\n");
    sb.append("    tidligereFodselsnummer: ").append(toIndentedString(tidligereFodselsnummer)).append("\n");
    sb.append("    nesteFodselsnummer: ").append(toIndentedString(nesteFodselsnummer)).append("\n");
    sb.append("    semester: ").append(toIndentedString(semester)).append("\n");
    sb.append("    sammenslatt: ").append(toIndentedString(sammenslatt)).append("\n");
    sb.append("    behandletAvSamordnaOpptak: ").append(toIndentedString(behandletAvSamordnaOpptak)).append("\n");
    sb.append("    datoMeldtSamordnaOpptak: ").append(toIndentedString(datoMeldtSamordnaOpptak)).append("\n");
    sb.append("    bestillingsIdSamordnaOpptak: ").append(toIndentedString(bestillingsIdSamordnaOpptak)).append("\n");
    sb.append("    grunnlagsmerknad: ").append(toIndentedString(grunnlagsmerknad)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
