/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Fodselsnummer
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Fodselsnummer {

  @JsonProperty("fodselsdato")

  private Integer fodselsdato = null;

  @JsonProperty("personnummer")

  private Integer personnummer = null;
  public Fodselsnummer fodselsdato(Integer fodselsdato) {
    this.fodselsdato = fodselsdato;
    return this;
  }

  

  /**
  * Get fodselsdato
  * minimum: 0
  * maximum: 999999
  * @return fodselsdato
  **/
  @Schema(example = "15112", description = "")
  public Integer getFodselsdato() {
    return fodselsdato;
  }
  public void setFodselsdato(Integer fodselsdato) {
    this.fodselsdato = fodselsdato;
  }
  public Fodselsnummer personnummer(Integer personnummer) {
    this.personnummer = personnummer;
    return this;
  }

  

  /**
  * Get personnummer
  * minimum: 0
  * maximum: 99999
  * @return personnummer
  **/
  @Schema(example = "90267", description = "")
  public Integer getPersonnummer() {
    return personnummer;
  }
  public void setPersonnummer(Integer personnummer) {
    this.personnummer = personnummer;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fodselsnummer fodselsnummer = (Fodselsnummer) o;
    return Objects.equals(this.fodselsdato, fodselsnummer.fodselsdato) &&
        Objects.equals(this.personnummer, fodselsnummer.personnummer);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(fodselsdato, personnummer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fodselsnummer {\n");
    
    sb.append("    fodselsdato: ").append(toIndentedString(fodselsdato)).append("\n");
    sb.append("    personnummer: ").append(toIndentedString(personnummer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
