/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InstitusjonInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class InstitusjonInfo {

  @JsonProperty("institusjonstypekode")

  private String institusjonstypekode = null;

  @JsonProperty("bynavn")

  private String bynavn = null;

  @JsonProperty("regionnavn")

  private String regionnavn = null;

  @JsonProperty("alternativtInstitusjonsnavn")

  private String alternativtInstitusjonsnavn = null;

  @JsonProperty("erasmusinstitusjonskode")

  private String erasmusinstitusjonskode = null;

  @JsonProperty("schacHomeOrganization")

  private String schacHomeOrganization = null;

  @JsonProperty("godkjentBetalingssted")

  private Boolean godkjentBetalingssted = null;

  @JsonProperty("fusjonert")

  private Boolean fusjonert = null;

  @JsonProperty("telefonnummerMerknad")

  private String telefonnummerMerknad = null;
  public InstitusjonInfo institusjonstypekode(String institusjonstypekode) {
    this.institusjonstypekode = institusjonstypekode;
    return this;
  }

  

  /**
  * Get institusjonstypekode
  * @return institusjonstypekode
  **/
  @Schema(description = "")
  public String getInstitusjonstypekode() {
    return institusjonstypekode;
  }
  public void setInstitusjonstypekode(String institusjonstypekode) {
    this.institusjonstypekode = institusjonstypekode;
  }
  public InstitusjonInfo bynavn(String bynavn) {
    this.bynavn = bynavn;
    return this;
  }

  

  /**
  * Get bynavn
  * @return bynavn
  **/
  @Schema(description = "")
  public String getBynavn() {
    return bynavn;
  }
  public void setBynavn(String bynavn) {
    this.bynavn = bynavn;
  }
  public InstitusjonInfo regionnavn(String regionnavn) {
    this.regionnavn = regionnavn;
    return this;
  }

  

  /**
  * Get regionnavn
  * @return regionnavn
  **/
  @Schema(description = "")
  public String getRegionnavn() {
    return regionnavn;
  }
  public void setRegionnavn(String regionnavn) {
    this.regionnavn = regionnavn;
  }
  public InstitusjonInfo alternativtInstitusjonsnavn(String alternativtInstitusjonsnavn) {
    this.alternativtInstitusjonsnavn = alternativtInstitusjonsnavn;
    return this;
  }

  

  /**
  * Get alternativtInstitusjonsnavn
  * @return alternativtInstitusjonsnavn
  **/
  @Schema(description = "")
  public String getAlternativtInstitusjonsnavn() {
    return alternativtInstitusjonsnavn;
  }
  public void setAlternativtInstitusjonsnavn(String alternativtInstitusjonsnavn) {
    this.alternativtInstitusjonsnavn = alternativtInstitusjonsnavn;
  }
  public InstitusjonInfo erasmusinstitusjonskode(String erasmusinstitusjonskode) {
    this.erasmusinstitusjonskode = erasmusinstitusjonskode;
    return this;
  }

  

  /**
  * Get erasmusinstitusjonskode
  * @return erasmusinstitusjonskode
  **/
  @Schema(description = "")
  public String getErasmusinstitusjonskode() {
    return erasmusinstitusjonskode;
  }
  public void setErasmusinstitusjonskode(String erasmusinstitusjonskode) {
    this.erasmusinstitusjonskode = erasmusinstitusjonskode;
  }
  public InstitusjonInfo schacHomeOrganization(String schacHomeOrganization) {
    this.schacHomeOrganization = schacHomeOrganization;
    return this;
  }

  

  /**
  * Get schacHomeOrganization
  * @return schacHomeOrganization
  **/
  @Schema(description = "")
  public String getSchacHomeOrganization() {
    return schacHomeOrganization;
  }
  public void setSchacHomeOrganization(String schacHomeOrganization) {
    this.schacHomeOrganization = schacHomeOrganization;
  }
  public InstitusjonInfo godkjentBetalingssted(Boolean godkjentBetalingssted) {
    this.godkjentBetalingssted = godkjentBetalingssted;
    return this;
  }

  

  /**
  * Get godkjentBetalingssted
  * @return godkjentBetalingssted
  **/
  @Schema(description = "")
  public Boolean isGodkjentBetalingssted() {
    return godkjentBetalingssted;
  }
  public void setGodkjentBetalingssted(Boolean godkjentBetalingssted) {
    this.godkjentBetalingssted = godkjentBetalingssted;
  }
  public InstitusjonInfo fusjonert(Boolean fusjonert) {
    this.fusjonert = fusjonert;
    return this;
  }

  

  /**
  * Get fusjonert
  * @return fusjonert
  **/
  @Schema(description = "")
  public Boolean isFusjonert() {
    return fusjonert;
  }
  public void setFusjonert(Boolean fusjonert) {
    this.fusjonert = fusjonert;
  }
  public InstitusjonInfo telefonnummerMerknad(String telefonnummerMerknad) {
    this.telefonnummerMerknad = telefonnummerMerknad;
    return this;
  }

  

  /**
  * Get telefonnummerMerknad
  * @return telefonnummerMerknad
  **/
  @Schema(description = "")
  public String getTelefonnummerMerknad() {
    return telefonnummerMerknad;
  }
  public void setTelefonnummerMerknad(String telefonnummerMerknad) {
    this.telefonnummerMerknad = telefonnummerMerknad;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstitusjonInfo institusjonInfo = (InstitusjonInfo) o;
    return Objects.equals(this.institusjonstypekode, institusjonInfo.institusjonstypekode) &&
        Objects.equals(this.bynavn, institusjonInfo.bynavn) &&
        Objects.equals(this.regionnavn, institusjonInfo.regionnavn) &&
        Objects.equals(this.alternativtInstitusjonsnavn, institusjonInfo.alternativtInstitusjonsnavn) &&
        Objects.equals(this.erasmusinstitusjonskode, institusjonInfo.erasmusinstitusjonskode) &&
        Objects.equals(this.schacHomeOrganization, institusjonInfo.schacHomeOrganization) &&
        Objects.equals(this.godkjentBetalingssted, institusjonInfo.godkjentBetalingssted) &&
        Objects.equals(this.fusjonert, institusjonInfo.fusjonert) &&
        Objects.equals(this.telefonnummerMerknad, institusjonInfo.telefonnummerMerknad);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(institusjonstypekode, bynavn, regionnavn, alternativtInstitusjonsnavn, erasmusinstitusjonskode, schacHomeOrganization, godkjentBetalingssted, fusjonert, telefonnummerMerknad);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstitusjonInfo {\n");
    
    sb.append("    institusjonstypekode: ").append(toIndentedString(institusjonstypekode)).append("\n");
    sb.append("    bynavn: ").append(toIndentedString(bynavn)).append("\n");
    sb.append("    regionnavn: ").append(toIndentedString(regionnavn)).append("\n");
    sb.append("    alternativtInstitusjonsnavn: ").append(toIndentedString(alternativtInstitusjonsnavn)).append("\n");
    sb.append("    erasmusinstitusjonskode: ").append(toIndentedString(erasmusinstitusjonskode)).append("\n");
    sb.append("    schacHomeOrganization: ").append(toIndentedString(schacHomeOrganization)).append("\n");
    sb.append("    godkjentBetalingssted: ").append(toIndentedString(godkjentBetalingssted)).append("\n");
    sb.append("    fusjonert: ").append(toIndentedString(fusjonert)).append("\n");
    sb.append("    telefonnummerMerknad: ").append(toIndentedString(telefonnummerMerknad)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
