/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ISCEDInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class ISCEDInfo {

  @JsonProperty("kode")

  private String kode = null;

  @JsonProperty("navn")

  private String navn = null;

  @JsonProperty("type")

  private Boolean type = null;

  @JsonProperty("narrowNavn")

  private String narrowNavn = null;

  @JsonProperty("narrowType")

  private Boolean narrowType = null;

  @JsonProperty("broadNavn")

  private String broadNavn = null;

  @JsonProperty("broadType")

  private Boolean broadType = null;
  public ISCEDInfo kode(String kode) {
    this.kode = kode;
    return this;
  }

  

  /**
  * Get kode
  * @return kode
  **/
  @Schema(description = "")
  public String getKode() {
    return kode;
  }
  public void setKode(String kode) {
    this.kode = kode;
  }
  public ISCEDInfo navn(String navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public String getNavn() {
    return navn;
  }
  public void setNavn(String navn) {
    this.navn = navn;
  }
  public ISCEDInfo type(Boolean type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(description = "")
  public Boolean isType() {
    return type;
  }
  public void setType(Boolean type) {
    this.type = type;
  }
  public ISCEDInfo narrowNavn(String narrowNavn) {
    this.narrowNavn = narrowNavn;
    return this;
  }

  

  /**
  * Get narrowNavn
  * @return narrowNavn
  **/
  @Schema(description = "")
  public String getNarrowNavn() {
    return narrowNavn;
  }
  public void setNarrowNavn(String narrowNavn) {
    this.narrowNavn = narrowNavn;
  }
  public ISCEDInfo narrowType(Boolean narrowType) {
    this.narrowType = narrowType;
    return this;
  }

  

  /**
  * Get narrowType
  * @return narrowType
  **/
  @Schema(description = "")
  public Boolean isNarrowType() {
    return narrowType;
  }
  public void setNarrowType(Boolean narrowType) {
    this.narrowType = narrowType;
  }
  public ISCEDInfo broadNavn(String broadNavn) {
    this.broadNavn = broadNavn;
    return this;
  }

  

  /**
  * Get broadNavn
  * @return broadNavn
  **/
  @Schema(description = "")
  public String getBroadNavn() {
    return broadNavn;
  }
  public void setBroadNavn(String broadNavn) {
    this.broadNavn = broadNavn;
  }
  public ISCEDInfo broadType(Boolean broadType) {
    this.broadType = broadType;
    return this;
  }

  

  /**
  * Get broadType
  * @return broadType
  **/
  @Schema(description = "")
  public Boolean isBroadType() {
    return broadType;
  }
  public void setBroadType(Boolean broadType) {
    this.broadType = broadType;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ISCEDInfo isCEDInfo = (ISCEDInfo) o;
    return Objects.equals(this.kode, isCEDInfo.kode) &&
        Objects.equals(this.navn, isCEDInfo.navn) &&
        Objects.equals(this.type, isCEDInfo.type) &&
        Objects.equals(this.narrowNavn, isCEDInfo.narrowNavn) &&
        Objects.equals(this.narrowType, isCEDInfo.narrowType) &&
        Objects.equals(this.broadNavn, isCEDInfo.broadNavn) &&
        Objects.equals(this.broadType, isCEDInfo.broadType);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(kode, navn, type, narrowNavn, narrowType, broadNavn, broadType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ISCEDInfo {\n");
    
    sb.append("    kode: ").append(toIndentedString(kode)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    narrowNavn: ").append(toIndentedString(narrowNavn)).append("\n");
    sb.append("    narrowType: ").append(toIndentedString(narrowType)).append("\n");
    sb.append("    broadNavn: ").append(toIndentedString(broadNavn)).append("\n");
    sb.append("    broadType: ").append(toIndentedString(broadType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
