/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.KullId;
import no.bibsys.fs.model.LmsInfo;
import no.bibsys.fs.model.SprakFelter;

/**
 * Kull
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Kull {

  @JsonProperty("id")

  private KullId id = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("aktiv")

  private Boolean aktiv = null;

  @JsonProperty("lms")

  private LmsInfo lms = null;
  public Kull id(KullId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public KullId getId() {
    return id;
  }
  public void setId(KullId id) {
    this.id = id;
  }
  public Kull navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public Kull aktiv(Boolean aktiv) {
    this.aktiv = aktiv;
    return this;
  }

  

  /**
  * Get aktiv
  * @return aktiv
  **/
  @Schema(description = "")
  public Boolean isAktiv() {
    return aktiv;
  }
  public void setAktiv(Boolean aktiv) {
    this.aktiv = aktiv;
  }
  public Kull lms(LmsInfo lms) {
    this.lms = lms;
    return this;
  }

  

  /**
  * Get lms
  * @return lms
  **/
  @Schema(description = "")
  public LmsInfo getLms() {
    return lms;
  }
  public void setLms(LmsInfo lms) {
    this.lms = lms;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Kull kull = (Kull) o;
    return Objects.equals(this.id, kull.id) &&
        Objects.equals(this.navn, kull.navn) &&
        Objects.equals(this.aktiv, kull.aktiv) &&
        Objects.equals(this.lms, kull.lms);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, navn, aktiv, lms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Kull {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
    sb.append("    lms: ").append(toIndentedString(lms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
