/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.KvalifikasjonsgrunnlagId;

/**
 * Kvalifikasjonsgrunnlag
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Kvalifikasjonsgrunnlag {

  @JsonProperty("id")

  private KvalifikasjonsgrunnlagId id = null;

  @JsonProperty("navn")

  private String navn = null;

  @JsonProperty("gskBrukes")

  private Boolean gskBrukes = null;

  @JsonProperty("kompetanseregelverkBrukes")

  private Boolean kompetanseregelverkBrukes = null;

  @JsonProperty("rangeringsregelverkBrukes")

  private Boolean rangeringsregelverkBrukes = null;

  @JsonProperty("skolepoengForventes")

  private Boolean skolepoengForventes = null;

  @JsonProperty("nasjonalOpptaksmodell")

  private Boolean nasjonalOpptaksmodell = null;

  @JsonProperty("forbedringTillatt")

  private Boolean forbedringTillatt = null;

  @JsonProperty("prioritetSamordnaOpptak")

  private Integer prioritetSamordnaOpptak = null;

  @JsonProperty("gskVedtakRangering")

  private Integer gskVedtakRangering = null;

  @JsonProperty("felles")

  private Boolean felles = null;

  @JsonProperty("merknad")

  private String merknad = null;

  @JsonProperty("arUtgatt")

  private Integer arUtgatt = null;

  @JsonProperty("fodselsArUtgatt")

  private Integer fodselsArUtgatt = null;
  public Kvalifikasjonsgrunnlag id(KvalifikasjonsgrunnlagId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public KvalifikasjonsgrunnlagId getId() {
    return id;
  }
  public void setId(KvalifikasjonsgrunnlagId id) {
    this.id = id;
  }
  public Kvalifikasjonsgrunnlag navn(String navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public String getNavn() {
    return navn;
  }
  public void setNavn(String navn) {
    this.navn = navn;
  }
  public Kvalifikasjonsgrunnlag gskBrukes(Boolean gskBrukes) {
    this.gskBrukes = gskBrukes;
    return this;
  }

  

  /**
  * Get gskBrukes
  * @return gskBrukes
  **/
  @Schema(description = "")
  public Boolean isGskBrukes() {
    return gskBrukes;
  }
  public void setGskBrukes(Boolean gskBrukes) {
    this.gskBrukes = gskBrukes;
  }
  public Kvalifikasjonsgrunnlag kompetanseregelverkBrukes(Boolean kompetanseregelverkBrukes) {
    this.kompetanseregelverkBrukes = kompetanseregelverkBrukes;
    return this;
  }

  

  /**
  * Get kompetanseregelverkBrukes
  * @return kompetanseregelverkBrukes
  **/
  @Schema(description = "")
  public Boolean isKompetanseregelverkBrukes() {
    return kompetanseregelverkBrukes;
  }
  public void setKompetanseregelverkBrukes(Boolean kompetanseregelverkBrukes) {
    this.kompetanseregelverkBrukes = kompetanseregelverkBrukes;
  }
  public Kvalifikasjonsgrunnlag rangeringsregelverkBrukes(Boolean rangeringsregelverkBrukes) {
    this.rangeringsregelverkBrukes = rangeringsregelverkBrukes;
    return this;
  }

  

  /**
  * Get rangeringsregelverkBrukes
  * @return rangeringsregelverkBrukes
  **/
  @Schema(description = "")
  public Boolean isRangeringsregelverkBrukes() {
    return rangeringsregelverkBrukes;
  }
  public void setRangeringsregelverkBrukes(Boolean rangeringsregelverkBrukes) {
    this.rangeringsregelverkBrukes = rangeringsregelverkBrukes;
  }
  public Kvalifikasjonsgrunnlag skolepoengForventes(Boolean skolepoengForventes) {
    this.skolepoengForventes = skolepoengForventes;
    return this;
  }

  

  /**
  * Get skolepoengForventes
  * @return skolepoengForventes
  **/
  @Schema(description = "")
  public Boolean isSkolepoengForventes() {
    return skolepoengForventes;
  }
  public void setSkolepoengForventes(Boolean skolepoengForventes) {
    this.skolepoengForventes = skolepoengForventes;
  }
  public Kvalifikasjonsgrunnlag nasjonalOpptaksmodell(Boolean nasjonalOpptaksmodell) {
    this.nasjonalOpptaksmodell = nasjonalOpptaksmodell;
    return this;
  }

  

  /**
  * Get nasjonalOpptaksmodell
  * @return nasjonalOpptaksmodell
  **/
  @Schema(description = "")
  public Boolean isNasjonalOpptaksmodell() {
    return nasjonalOpptaksmodell;
  }
  public void setNasjonalOpptaksmodell(Boolean nasjonalOpptaksmodell) {
    this.nasjonalOpptaksmodell = nasjonalOpptaksmodell;
  }
  public Kvalifikasjonsgrunnlag forbedringTillatt(Boolean forbedringTillatt) {
    this.forbedringTillatt = forbedringTillatt;
    return this;
  }

  

  /**
  * Get forbedringTillatt
  * @return forbedringTillatt
  **/
  @Schema(description = "")
  public Boolean isForbedringTillatt() {
    return forbedringTillatt;
  }
  public void setForbedringTillatt(Boolean forbedringTillatt) {
    this.forbedringTillatt = forbedringTillatt;
  }
  public Kvalifikasjonsgrunnlag prioritetSamordnaOpptak(Integer prioritetSamordnaOpptak) {
    this.prioritetSamordnaOpptak = prioritetSamordnaOpptak;
    return this;
  }

  

  /**
  * Get prioritetSamordnaOpptak
  * @return prioritetSamordnaOpptak
  **/
  @Schema(description = "")
  public Integer getPrioritetSamordnaOpptak() {
    return prioritetSamordnaOpptak;
  }
  public void setPrioritetSamordnaOpptak(Integer prioritetSamordnaOpptak) {
    this.prioritetSamordnaOpptak = prioritetSamordnaOpptak;
  }
  public Kvalifikasjonsgrunnlag gskVedtakRangering(Integer gskVedtakRangering) {
    this.gskVedtakRangering = gskVedtakRangering;
    return this;
  }

  

  /**
  * Get gskVedtakRangering
  * @return gskVedtakRangering
  **/
  @Schema(description = "")
  public Integer getGskVedtakRangering() {
    return gskVedtakRangering;
  }
  public void setGskVedtakRangering(Integer gskVedtakRangering) {
    this.gskVedtakRangering = gskVedtakRangering;
  }
  public Kvalifikasjonsgrunnlag felles(Boolean felles) {
    this.felles = felles;
    return this;
  }

  

  /**
  * Get felles
  * @return felles
  **/
  @Schema(description = "")
  public Boolean isFelles() {
    return felles;
  }
  public void setFelles(Boolean felles) {
    this.felles = felles;
  }
  public Kvalifikasjonsgrunnlag merknad(String merknad) {
    this.merknad = merknad;
    return this;
  }

  

  /**
  * Get merknad
  * @return merknad
  **/
  @Schema(description = "")
  public String getMerknad() {
    return merknad;
  }
  public void setMerknad(String merknad) {
    this.merknad = merknad;
  }
  public Kvalifikasjonsgrunnlag arUtgatt(Integer arUtgatt) {
    this.arUtgatt = arUtgatt;
    return this;
  }

  

  /**
  * Get arUtgatt
  * @return arUtgatt
  **/
  @Schema(description = "")
  public Integer getArUtgatt() {
    return arUtgatt;
  }
  public void setArUtgatt(Integer arUtgatt) {
    this.arUtgatt = arUtgatt;
  }
  public Kvalifikasjonsgrunnlag fodselsArUtgatt(Integer fodselsArUtgatt) {
    this.fodselsArUtgatt = fodselsArUtgatt;
    return this;
  }

  

  /**
  * Get fodselsArUtgatt
  * @return fodselsArUtgatt
  **/
  @Schema(description = "")
  public Integer getFodselsArUtgatt() {
    return fodselsArUtgatt;
  }
  public void setFodselsArUtgatt(Integer fodselsArUtgatt) {
    this.fodselsArUtgatt = fodselsArUtgatt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Kvalifikasjonsgrunnlag kvalifikasjonsgrunnlag = (Kvalifikasjonsgrunnlag) o;
    return Objects.equals(this.id, kvalifikasjonsgrunnlag.id) &&
        Objects.equals(this.navn, kvalifikasjonsgrunnlag.navn) &&
        Objects.equals(this.gskBrukes, kvalifikasjonsgrunnlag.gskBrukes) &&
        Objects.equals(this.kompetanseregelverkBrukes, kvalifikasjonsgrunnlag.kompetanseregelverkBrukes) &&
        Objects.equals(this.rangeringsregelverkBrukes, kvalifikasjonsgrunnlag.rangeringsregelverkBrukes) &&
        Objects.equals(this.skolepoengForventes, kvalifikasjonsgrunnlag.skolepoengForventes) &&
        Objects.equals(this.nasjonalOpptaksmodell, kvalifikasjonsgrunnlag.nasjonalOpptaksmodell) &&
        Objects.equals(this.forbedringTillatt, kvalifikasjonsgrunnlag.forbedringTillatt) &&
        Objects.equals(this.prioritetSamordnaOpptak, kvalifikasjonsgrunnlag.prioritetSamordnaOpptak) &&
        Objects.equals(this.gskVedtakRangering, kvalifikasjonsgrunnlag.gskVedtakRangering) &&
        Objects.equals(this.felles, kvalifikasjonsgrunnlag.felles) &&
        Objects.equals(this.merknad, kvalifikasjonsgrunnlag.merknad) &&
        Objects.equals(this.arUtgatt, kvalifikasjonsgrunnlag.arUtgatt) &&
        Objects.equals(this.fodselsArUtgatt, kvalifikasjonsgrunnlag.fodselsArUtgatt);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, navn, gskBrukes, kompetanseregelverkBrukes, rangeringsregelverkBrukes, skolepoengForventes, nasjonalOpptaksmodell, forbedringTillatt, prioritetSamordnaOpptak, gskVedtakRangering, felles, merknad, arUtgatt, fodselsArUtgatt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Kvalifikasjonsgrunnlag {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    gskBrukes: ").append(toIndentedString(gskBrukes)).append("\n");
    sb.append("    kompetanseregelverkBrukes: ").append(toIndentedString(kompetanseregelverkBrukes)).append("\n");
    sb.append("    rangeringsregelverkBrukes: ").append(toIndentedString(rangeringsregelverkBrukes)).append("\n");
    sb.append("    skolepoengForventes: ").append(toIndentedString(skolepoengForventes)).append("\n");
    sb.append("    nasjonalOpptaksmodell: ").append(toIndentedString(nasjonalOpptaksmodell)).append("\n");
    sb.append("    forbedringTillatt: ").append(toIndentedString(forbedringTillatt)).append("\n");
    sb.append("    prioritetSamordnaOpptak: ").append(toIndentedString(prioritetSamordnaOpptak)).append("\n");
    sb.append("    gskVedtakRangering: ").append(toIndentedString(gskVedtakRangering)).append("\n");
    sb.append("    felles: ").append(toIndentedString(felles)).append("\n");
    sb.append("    merknad: ").append(toIndentedString(merknad)).append("\n");
    sb.append("    arUtgatt: ").append(toIndentedString(arUtgatt)).append("\n");
    sb.append("    fodselsArUtgatt: ").append(toIndentedString(fodselsArUtgatt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
