/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * NSDFagTypeInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class NSDFagTypeInfo {

  @JsonProperty("kode")

  private String kode = null;

  @JsonProperty("navn")

  private String navn = null;

  @JsonProperty("hoyereUtdanning")

  private Boolean hoyereUtdanning = null;

  @JsonProperty("yrkesfag")

  private Boolean yrkesfag = null;

  @JsonProperty("rekkefolge")

  private String rekkefolge = null;
  public NSDFagTypeInfo kode(String kode) {
    this.kode = kode;
    return this;
  }

  

  /**
  * Get kode
  * @return kode
  **/
  @Schema(description = "")
  public String getKode() {
    return kode;
  }
  public void setKode(String kode) {
    this.kode = kode;
  }
  public NSDFagTypeInfo navn(String navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public String getNavn() {
    return navn;
  }
  public void setNavn(String navn) {
    this.navn = navn;
  }
  public NSDFagTypeInfo hoyereUtdanning(Boolean hoyereUtdanning) {
    this.hoyereUtdanning = hoyereUtdanning;
    return this;
  }

  

  /**
  * Get hoyereUtdanning
  * @return hoyereUtdanning
  **/
  @Schema(description = "")
  public Boolean isHoyereUtdanning() {
    return hoyereUtdanning;
  }
  public void setHoyereUtdanning(Boolean hoyereUtdanning) {
    this.hoyereUtdanning = hoyereUtdanning;
  }
  public NSDFagTypeInfo yrkesfag(Boolean yrkesfag) {
    this.yrkesfag = yrkesfag;
    return this;
  }

  

  /**
  * Get yrkesfag
  * @return yrkesfag
  **/
  @Schema(description = "")
  public Boolean isYrkesfag() {
    return yrkesfag;
  }
  public void setYrkesfag(Boolean yrkesfag) {
    this.yrkesfag = yrkesfag;
  }
  public NSDFagTypeInfo rekkefolge(String rekkefolge) {
    this.rekkefolge = rekkefolge;
    return this;
  }

  

  /**
  * Get rekkefolge
  * @return rekkefolge
  **/
  @Schema(description = "")
  public String getRekkefolge() {
    return rekkefolge;
  }
  public void setRekkefolge(String rekkefolge) {
    this.rekkefolge = rekkefolge;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NSDFagTypeInfo nsDFagTypeInfo = (NSDFagTypeInfo) o;
    return Objects.equals(this.kode, nsDFagTypeInfo.kode) &&
        Objects.equals(this.navn, nsDFagTypeInfo.navn) &&
        Objects.equals(this.hoyereUtdanning, nsDFagTypeInfo.hoyereUtdanning) &&
        Objects.equals(this.yrkesfag, nsDFagTypeInfo.yrkesfag) &&
        Objects.equals(this.rekkefolge, nsDFagTypeInfo.rekkefolge);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(kode, navn, hoyereUtdanning, yrkesfag, rekkefolge);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NSDFagTypeInfo {\n");
    
    sb.append("    kode: ").append(toIndentedString(kode)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    hoyereUtdanning: ").append(toIndentedString(hoyereUtdanning)).append("\n");
    sb.append("    yrkesfag: ").append(toIndentedString(yrkesfag)).append("\n");
    sb.append("    rekkefolge: ").append(toIndentedString(rekkefolge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
