/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.Adresser;
import no.bibsys.fs.model.BIBSYSBestStedInfo;
import no.bibsys.fs.model.DatoIntervall;
import no.bibsys.fs.model.Eposter;
import no.bibsys.fs.model.Id2;
import no.bibsys.fs.model.InstitusjonInfo;
import no.bibsys.fs.model.Links;
import no.bibsys.fs.model.LmsInfo;
import no.bibsys.fs.model.OrganisasjonsenhetId;
import no.bibsys.fs.model.SprakFelter;
import no.bibsys.fs.model.Telefoner;
import no.bibsys.fs.model.Urler;

/**
 * Organisasjonsenhet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Organisasjonsenhet {

  @JsonProperty("id")

  private OrganisasjonsenhetId id = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("organisasjonsenheter")

  private Links organisasjonsenheter = null;

  @JsonProperty("institusjonsinformasjon")

  private InstitusjonInfo institusjonsinformasjon = null;

  @JsonProperty("adresser")

  private Adresser adresser = null;

  @JsonProperty("telefoner")

  private Telefoner telefoner = null;

  @JsonProperty("eposter")

  private Eposter eposter = null;

  @JsonProperty("urler")

  private Urler urler = null;

  @JsonProperty("land")

  private Id2 land = null;

  @JsonProperty("periode")

  private DatoIntervall periode = null;

  @JsonProperty("lms")

  private LmsInfo lms = null;

  @JsonProperty("bibsysBestillersted")

  private BIBSYSBestStedInfo bibsysBestillersted = null;

  @JsonProperty("merknad")

  private SprakFelter merknad = null;

  @JsonProperty("generellMerknad")

  private String generellMerknad = null;

  @JsonProperty("akronym")

  private String akronym = null;

  @JsonProperty("organisasjonsnivakode")

  private String organisasjonsnivakode = null;

  @JsonProperty("organisasjonsnivanavn")

  private String organisasjonsnivanavn = null;

  @JsonProperty("nsdAvdelingskode")

  private String nsdAvdelingskode = null;

  @JsonProperty("eiertypekode")

  private String eiertypekode = null;

  @JsonProperty("eiertypenavn")

  private String eiertypenavn = null;

  @JsonProperty("nsdInstitusjonskode")

  private Integer nsdInstitusjonskode = null;

  @JsonProperty("organisasjonsnummer")

  private Integer organisasjonsnummer = null;

  @JsonProperty("organisasjonskodeKonvertering")

  private String organisasjonskodeKonvertering = null;

  @JsonProperty("fakultetsfarge")

  private String fakultetsfarge = null;

  @JsonProperty("aktiv")

  private Boolean aktiv = null;

  @JsonProperty("stemmerettsted")

  private Boolean stemmerettsted = null;

  @JsonProperty("internSensurEpost")

  private Boolean internSensurEpost = null;

  @JsonProperty("eksternSensurEpost")

  private Boolean eksternSensurEpost = null;

  @JsonProperty("samletKlagegruppe")

  private Boolean samletKlagegruppe = null;

  @JsonProperty("felles")

  private Boolean felles = null;
  public Organisasjonsenhet id(OrganisasjonsenhetId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public OrganisasjonsenhetId getId() {
    return id;
  }
  public void setId(OrganisasjonsenhetId id) {
    this.id = id;
  }
  public Organisasjonsenhet navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public Organisasjonsenhet organisasjonsenheter(Links organisasjonsenheter) {
    this.organisasjonsenheter = organisasjonsenheter;
    return this;
  }

  

  /**
  * Get organisasjonsenheter
  * @return organisasjonsenheter
  **/
  @Schema(description = "")
  public Links getOrganisasjonsenheter() {
    return organisasjonsenheter;
  }
  public void setOrganisasjonsenheter(Links organisasjonsenheter) {
    this.organisasjonsenheter = organisasjonsenheter;
  }
  public Organisasjonsenhet institusjonsinformasjon(InstitusjonInfo institusjonsinformasjon) {
    this.institusjonsinformasjon = institusjonsinformasjon;
    return this;
  }

  

  /**
  * Get institusjonsinformasjon
  * @return institusjonsinformasjon
  **/
  @Schema(description = "")
  public InstitusjonInfo getInstitusjonsinformasjon() {
    return institusjonsinformasjon;
  }
  public void setInstitusjonsinformasjon(InstitusjonInfo institusjonsinformasjon) {
    this.institusjonsinformasjon = institusjonsinformasjon;
  }
  public Organisasjonsenhet adresser(Adresser adresser) {
    this.adresser = adresser;
    return this;
  }

  

  /**
  * Get adresser
  * @return adresser
  **/
  @Schema(description = "")
  public Adresser getAdresser() {
    return adresser;
  }
  public void setAdresser(Adresser adresser) {
    this.adresser = adresser;
  }
  public Organisasjonsenhet telefoner(Telefoner telefoner) {
    this.telefoner = telefoner;
    return this;
  }

  

  /**
  * Get telefoner
  * @return telefoner
  **/
  @Schema(description = "")
  public Telefoner getTelefoner() {
    return telefoner;
  }
  public void setTelefoner(Telefoner telefoner) {
    this.telefoner = telefoner;
  }
  public Organisasjonsenhet eposter(Eposter eposter) {
    this.eposter = eposter;
    return this;
  }

  

  /**
  * Get eposter
  * @return eposter
  **/
  @Schema(description = "")
  public Eposter getEposter() {
    return eposter;
  }
  public void setEposter(Eposter eposter) {
    this.eposter = eposter;
  }
  public Organisasjonsenhet urler(Urler urler) {
    this.urler = urler;
    return this;
  }

  

  /**
  * Get urler
  * @return urler
  **/
  @Schema(description = "")
  public Urler getUrler() {
    return urler;
  }
  public void setUrler(Urler urler) {
    this.urler = urler;
  }
  public Organisasjonsenhet land(Id2 land) {
    this.land = land;
    return this;
  }

  

  /**
  * Get land
  * @return land
  **/
  @Schema(description = "")
  public Id2 getLand() {
    return land;
  }
  public void setLand(Id2 land) {
    this.land = land;
  }
  public Organisasjonsenhet periode(DatoIntervall periode) {
    this.periode = periode;
    return this;
  }

  

  /**
  * Get periode
  * @return periode
  **/
  @Schema(description = "")
  public DatoIntervall getPeriode() {
    return periode;
  }
  public void setPeriode(DatoIntervall periode) {
    this.periode = periode;
  }
  public Organisasjonsenhet lms(LmsInfo lms) {
    this.lms = lms;
    return this;
  }

  

  /**
  * Get lms
  * @return lms
  **/
  @Schema(description = "")
  public LmsInfo getLms() {
    return lms;
  }
  public void setLms(LmsInfo lms) {
    this.lms = lms;
  }
  public Organisasjonsenhet bibsysBestillersted(BIBSYSBestStedInfo bibsysBestillersted) {
    this.bibsysBestillersted = bibsysBestillersted;
    return this;
  }

  

  /**
  * Get bibsysBestillersted
  * @return bibsysBestillersted
  **/
  @Schema(description = "")
  public BIBSYSBestStedInfo getBibsysBestillersted() {
    return bibsysBestillersted;
  }
  public void setBibsysBestillersted(BIBSYSBestStedInfo bibsysBestillersted) {
    this.bibsysBestillersted = bibsysBestillersted;
  }
  public Organisasjonsenhet merknad(SprakFelter merknad) {
    this.merknad = merknad;
    return this;
  }

  

  /**
  * Get merknad
  * @return merknad
  **/
  @Schema(description = "")
  public SprakFelter getMerknad() {
    return merknad;
  }
  public void setMerknad(SprakFelter merknad) {
    this.merknad = merknad;
  }
  public Organisasjonsenhet generellMerknad(String generellMerknad) {
    this.generellMerknad = generellMerknad;
    return this;
  }

  

  /**
  * Get generellMerknad
  * @return generellMerknad
  **/
  @Schema(description = "")
  public String getGenerellMerknad() {
    return generellMerknad;
  }
  public void setGenerellMerknad(String generellMerknad) {
    this.generellMerknad = generellMerknad;
  }
  public Organisasjonsenhet akronym(String akronym) {
    this.akronym = akronym;
    return this;
  }

  

  /**
  * Get akronym
  * @return akronym
  **/
  @Schema(description = "")
  public String getAkronym() {
    return akronym;
  }
  public void setAkronym(String akronym) {
    this.akronym = akronym;
  }
  public Organisasjonsenhet organisasjonsnivakode(String organisasjonsnivakode) {
    this.organisasjonsnivakode = organisasjonsnivakode;
    return this;
  }

  

  /**
  * Get organisasjonsnivakode
  * @return organisasjonsnivakode
  **/
  @Schema(description = "")
  public String getOrganisasjonsnivakode() {
    return organisasjonsnivakode;
  }
  public void setOrganisasjonsnivakode(String organisasjonsnivakode) {
    this.organisasjonsnivakode = organisasjonsnivakode;
  }
  public Organisasjonsenhet organisasjonsnivanavn(String organisasjonsnivanavn) {
    this.organisasjonsnivanavn = organisasjonsnivanavn;
    return this;
  }

  

  /**
  * Get organisasjonsnivanavn
  * @return organisasjonsnivanavn
  **/
  @Schema(description = "")
  public String getOrganisasjonsnivanavn() {
    return organisasjonsnivanavn;
  }
  public void setOrganisasjonsnivanavn(String organisasjonsnivanavn) {
    this.organisasjonsnivanavn = organisasjonsnivanavn;
  }
  public Organisasjonsenhet nsdAvdelingskode(String nsdAvdelingskode) {
    this.nsdAvdelingskode = nsdAvdelingskode;
    return this;
  }

  

  /**
  * Get nsdAvdelingskode
  * @return nsdAvdelingskode
  **/
  @Schema(description = "")
  public String getNsdAvdelingskode() {
    return nsdAvdelingskode;
  }
  public void setNsdAvdelingskode(String nsdAvdelingskode) {
    this.nsdAvdelingskode = nsdAvdelingskode;
  }
  public Organisasjonsenhet eiertypekode(String eiertypekode) {
    this.eiertypekode = eiertypekode;
    return this;
  }

  

  /**
  * Get eiertypekode
  * @return eiertypekode
  **/
  @Schema(description = "")
  public String getEiertypekode() {
    return eiertypekode;
  }
  public void setEiertypekode(String eiertypekode) {
    this.eiertypekode = eiertypekode;
  }
  public Organisasjonsenhet eiertypenavn(String eiertypenavn) {
    this.eiertypenavn = eiertypenavn;
    return this;
  }

  

  /**
  * Get eiertypenavn
  * @return eiertypenavn
  **/
  @Schema(description = "")
  public String getEiertypenavn() {
    return eiertypenavn;
  }
  public void setEiertypenavn(String eiertypenavn) {
    this.eiertypenavn = eiertypenavn;
  }
  public Organisasjonsenhet nsdInstitusjonskode(Integer nsdInstitusjonskode) {
    this.nsdInstitusjonskode = nsdInstitusjonskode;
    return this;
  }

  

  /**
  * Get nsdInstitusjonskode
  * @return nsdInstitusjonskode
  **/
  @Schema(description = "")
  public Integer getNsdInstitusjonskode() {
    return nsdInstitusjonskode;
  }
  public void setNsdInstitusjonskode(Integer nsdInstitusjonskode) {
    this.nsdInstitusjonskode = nsdInstitusjonskode;
  }
  public Organisasjonsenhet organisasjonsnummer(Integer organisasjonsnummer) {
    this.organisasjonsnummer = organisasjonsnummer;
    return this;
  }

  

  /**
  * Get organisasjonsnummer
  * @return organisasjonsnummer
  **/
  @Schema(description = "")
  public Integer getOrganisasjonsnummer() {
    return organisasjonsnummer;
  }
  public void setOrganisasjonsnummer(Integer organisasjonsnummer) {
    this.organisasjonsnummer = organisasjonsnummer;
  }
  public Organisasjonsenhet organisasjonskodeKonvertering(String organisasjonskodeKonvertering) {
    this.organisasjonskodeKonvertering = organisasjonskodeKonvertering;
    return this;
  }

  

  /**
  * Get organisasjonskodeKonvertering
  * @return organisasjonskodeKonvertering
  **/
  @Schema(description = "")
  public String getOrganisasjonskodeKonvertering() {
    return organisasjonskodeKonvertering;
  }
  public void setOrganisasjonskodeKonvertering(String organisasjonskodeKonvertering) {
    this.organisasjonskodeKonvertering = organisasjonskodeKonvertering;
  }
  public Organisasjonsenhet fakultetsfarge(String fakultetsfarge) {
    this.fakultetsfarge = fakultetsfarge;
    return this;
  }

  

  /**
  * Get fakultetsfarge
  * @return fakultetsfarge
  **/
  @Schema(description = "")
  public String getFakultetsfarge() {
    return fakultetsfarge;
  }
  public void setFakultetsfarge(String fakultetsfarge) {
    this.fakultetsfarge = fakultetsfarge;
  }
  public Organisasjonsenhet aktiv(Boolean aktiv) {
    this.aktiv = aktiv;
    return this;
  }

  

  /**
  * Get aktiv
  * @return aktiv
  **/
  @Schema(description = "")
  public Boolean isAktiv() {
    return aktiv;
  }
  public void setAktiv(Boolean aktiv) {
    this.aktiv = aktiv;
  }
  public Organisasjonsenhet stemmerettsted(Boolean stemmerettsted) {
    this.stemmerettsted = stemmerettsted;
    return this;
  }

  

  /**
  * Get stemmerettsted
  * @return stemmerettsted
  **/
  @Schema(description = "")
  public Boolean isStemmerettsted() {
    return stemmerettsted;
  }
  public void setStemmerettsted(Boolean stemmerettsted) {
    this.stemmerettsted = stemmerettsted;
  }
  public Organisasjonsenhet internSensurEpost(Boolean internSensurEpost) {
    this.internSensurEpost = internSensurEpost;
    return this;
  }

  

  /**
  * Get internSensurEpost
  * @return internSensurEpost
  **/
  @Schema(description = "")
  public Boolean isInternSensurEpost() {
    return internSensurEpost;
  }
  public void setInternSensurEpost(Boolean internSensurEpost) {
    this.internSensurEpost = internSensurEpost;
  }
  public Organisasjonsenhet eksternSensurEpost(Boolean eksternSensurEpost) {
    this.eksternSensurEpost = eksternSensurEpost;
    return this;
  }

  

  /**
  * Get eksternSensurEpost
  * @return eksternSensurEpost
  **/
  @Schema(description = "")
  public Boolean isEksternSensurEpost() {
    return eksternSensurEpost;
  }
  public void setEksternSensurEpost(Boolean eksternSensurEpost) {
    this.eksternSensurEpost = eksternSensurEpost;
  }
  public Organisasjonsenhet samletKlagegruppe(Boolean samletKlagegruppe) {
    this.samletKlagegruppe = samletKlagegruppe;
    return this;
  }

  

  /**
  * Get samletKlagegruppe
  * @return samletKlagegruppe
  **/
  @Schema(description = "")
  public Boolean isSamletKlagegruppe() {
    return samletKlagegruppe;
  }
  public void setSamletKlagegruppe(Boolean samletKlagegruppe) {
    this.samletKlagegruppe = samletKlagegruppe;
  }
  public Organisasjonsenhet felles(Boolean felles) {
    this.felles = felles;
    return this;
  }

  

  /**
  * Get felles
  * @return felles
  **/
  @Schema(description = "")
  public Boolean isFelles() {
    return felles;
  }
  public void setFelles(Boolean felles) {
    this.felles = felles;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Organisasjonsenhet organisasjonsenhet = (Organisasjonsenhet) o;
    return Objects.equals(this.id, organisasjonsenhet.id) &&
        Objects.equals(this.navn, organisasjonsenhet.navn) &&
        Objects.equals(this.organisasjonsenheter, organisasjonsenhet.organisasjonsenheter) &&
        Objects.equals(this.institusjonsinformasjon, organisasjonsenhet.institusjonsinformasjon) &&
        Objects.equals(this.adresser, organisasjonsenhet.adresser) &&
        Objects.equals(this.telefoner, organisasjonsenhet.telefoner) &&
        Objects.equals(this.eposter, organisasjonsenhet.eposter) &&
        Objects.equals(this.urler, organisasjonsenhet.urler) &&
        Objects.equals(this.land, organisasjonsenhet.land) &&
        Objects.equals(this.periode, organisasjonsenhet.periode) &&
        Objects.equals(this.lms, organisasjonsenhet.lms) &&
        Objects.equals(this.bibsysBestillersted, organisasjonsenhet.bibsysBestillersted) &&
        Objects.equals(this.merknad, organisasjonsenhet.merknad) &&
        Objects.equals(this.generellMerknad, organisasjonsenhet.generellMerknad) &&
        Objects.equals(this.akronym, organisasjonsenhet.akronym) &&
        Objects.equals(this.organisasjonsnivakode, organisasjonsenhet.organisasjonsnivakode) &&
        Objects.equals(this.organisasjonsnivanavn, organisasjonsenhet.organisasjonsnivanavn) &&
        Objects.equals(this.nsdAvdelingskode, organisasjonsenhet.nsdAvdelingskode) &&
        Objects.equals(this.eiertypekode, organisasjonsenhet.eiertypekode) &&
        Objects.equals(this.eiertypenavn, organisasjonsenhet.eiertypenavn) &&
        Objects.equals(this.nsdInstitusjonskode, organisasjonsenhet.nsdInstitusjonskode) &&
        Objects.equals(this.organisasjonsnummer, organisasjonsenhet.organisasjonsnummer) &&
        Objects.equals(this.organisasjonskodeKonvertering, organisasjonsenhet.organisasjonskodeKonvertering) &&
        Objects.equals(this.fakultetsfarge, organisasjonsenhet.fakultetsfarge) &&
        Objects.equals(this.aktiv, organisasjonsenhet.aktiv) &&
        Objects.equals(this.stemmerettsted, organisasjonsenhet.stemmerettsted) &&
        Objects.equals(this.internSensurEpost, organisasjonsenhet.internSensurEpost) &&
        Objects.equals(this.eksternSensurEpost, organisasjonsenhet.eksternSensurEpost) &&
        Objects.equals(this.samletKlagegruppe, organisasjonsenhet.samletKlagegruppe) &&
        Objects.equals(this.felles, organisasjonsenhet.felles);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, navn, organisasjonsenheter, institusjonsinformasjon, adresser, telefoner, eposter, urler, land, periode, lms, bibsysBestillersted, merknad, generellMerknad, akronym, organisasjonsnivakode, organisasjonsnivanavn, nsdAvdelingskode, eiertypekode, eiertypenavn, nsdInstitusjonskode, organisasjonsnummer, organisasjonskodeKonvertering, fakultetsfarge, aktiv, stemmerettsted, internSensurEpost, eksternSensurEpost, samletKlagegruppe, felles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organisasjonsenhet {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    organisasjonsenheter: ").append(toIndentedString(organisasjonsenheter)).append("\n");
    sb.append("    institusjonsinformasjon: ").append(toIndentedString(institusjonsinformasjon)).append("\n");
    sb.append("    adresser: ").append(toIndentedString(adresser)).append("\n");
    sb.append("    telefoner: ").append(toIndentedString(telefoner)).append("\n");
    sb.append("    eposter: ").append(toIndentedString(eposter)).append("\n");
    sb.append("    urler: ").append(toIndentedString(urler)).append("\n");
    sb.append("    land: ").append(toIndentedString(land)).append("\n");
    sb.append("    periode: ").append(toIndentedString(periode)).append("\n");
    sb.append("    lms: ").append(toIndentedString(lms)).append("\n");
    sb.append("    bibsysBestillersted: ").append(toIndentedString(bibsysBestillersted)).append("\n");
    sb.append("    merknad: ").append(toIndentedString(merknad)).append("\n");
    sb.append("    generellMerknad: ").append(toIndentedString(generellMerknad)).append("\n");
    sb.append("    akronym: ").append(toIndentedString(akronym)).append("\n");
    sb.append("    organisasjonsnivakode: ").append(toIndentedString(organisasjonsnivakode)).append("\n");
    sb.append("    organisasjonsnivanavn: ").append(toIndentedString(organisasjonsnivanavn)).append("\n");
    sb.append("    nsdAvdelingskode: ").append(toIndentedString(nsdAvdelingskode)).append("\n");
    sb.append("    eiertypekode: ").append(toIndentedString(eiertypekode)).append("\n");
    sb.append("    eiertypenavn: ").append(toIndentedString(eiertypenavn)).append("\n");
    sb.append("    nsdInstitusjonskode: ").append(toIndentedString(nsdInstitusjonskode)).append("\n");
    sb.append("    organisasjonsnummer: ").append(toIndentedString(organisasjonsnummer)).append("\n");
    sb.append("    organisasjonskodeKonvertering: ").append(toIndentedString(organisasjonskodeKonvertering)).append("\n");
    sb.append("    fakultetsfarge: ").append(toIndentedString(fakultetsfarge)).append("\n");
    sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
    sb.append("    stemmerettsted: ").append(toIndentedString(stemmerettsted)).append("\n");
    sb.append("    internSensurEpost: ").append(toIndentedString(internSensurEpost)).append("\n");
    sb.append("    eksternSensurEpost: ").append(toIndentedString(eksternSensurEpost)).append("\n");
    sb.append("    samletKlagegruppe: ").append(toIndentedString(samletKlagegruppe)).append("\n");
    sb.append("    felles: ").append(toIndentedString(felles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
