/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * Paginering
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Paginering {

  @JsonProperty("href")

  private String href = null;

  @JsonProperty("rel")

  private List<String> rel = null;
  public Paginering href(String href) {
    this.href = href;
    return this;
  }

  

  /**
  * Get href
  * @return href
  **/
  @Schema(example = "https://server/resource?page=[1..n]&limit=[0,1..1000]", description = "")
  public String getHref() {
    return href;
  }
  public void setHref(String href) {
    this.href = href;
  }
  public Paginering rel(List<String> rel) {
    this.rel = rel;
    return this;
  }

  public Paginering addRelItem(String relItem) {
    if (this.rel == null) {
      this.rel = new ArrayList<String>();
    }
    this.rel.add(relItem);
    return this;
  }

  /**
  * Get rel
  * @return rel
  **/
  @Schema(description = "")
  public List<String> getRel() {
    return rel;
  }
  public void setRel(List<String> rel) {
    this.rel = rel;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Paginering paginering = (Paginering) o;
    return Objects.equals(this.href, paginering.href) &&
        Objects.equals(this.rel, paginering.rel);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(href, rel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Paginering {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    rel: ").append(toIndentedString(rel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
