/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.DatoIntervall;
import no.bibsys.fs.model.Id2;
import no.bibsys.fs.model.PersonrolleId;

/**
 * Personrolle
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Personrolle {

  @JsonProperty("id")

  private PersonrolleId id = null;

  @JsonProperty("rolle")

  private Id2 rolle = null;

  @JsonProperty("periode")

  private DatoIntervall periode = null;

  @JsonProperty("studieprogram")

  private Id2 studieprogram = null;

  @JsonProperty("evuKurs")

  private Id2 evuKurs = null;

  @JsonProperty("undervisningsaktivitet")

  private Id2 undervisningsaktivitet = null;
  public Personrolle id(PersonrolleId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public PersonrolleId getId() {
    return id;
  }
  public void setId(PersonrolleId id) {
    this.id = id;
  }
  public Personrolle rolle(Id2 rolle) {
    this.rolle = rolle;
    return this;
  }

  

  /**
  * Get rolle
  * @return rolle
  **/
  @Schema(description = "")
  public Id2 getRolle() {
    return rolle;
  }
  public void setRolle(Id2 rolle) {
    this.rolle = rolle;
  }
  public Personrolle periode(DatoIntervall periode) {
    this.periode = periode;
    return this;
  }

  

  /**
  * Get periode
  * @return periode
  **/
  @Schema(description = "")
  public DatoIntervall getPeriode() {
    return periode;
  }
  public void setPeriode(DatoIntervall periode) {
    this.periode = periode;
  }
  public Personrolle studieprogram(Id2 studieprogram) {
    this.studieprogram = studieprogram;
    return this;
  }

  

  /**
  * Get studieprogram
  * @return studieprogram
  **/
  @Schema(description = "")
  public Id2 getStudieprogram() {
    return studieprogram;
  }
  public void setStudieprogram(Id2 studieprogram) {
    this.studieprogram = studieprogram;
  }
  public Personrolle evuKurs(Id2 evuKurs) {
    this.evuKurs = evuKurs;
    return this;
  }

  

  /**
  * Get evuKurs
  * @return evuKurs
  **/
  @Schema(description = "")
  public Id2 getEvuKurs() {
    return evuKurs;
  }
  public void setEvuKurs(Id2 evuKurs) {
    this.evuKurs = evuKurs;
  }
  public Personrolle undervisningsaktivitet(Id2 undervisningsaktivitet) {
    this.undervisningsaktivitet = undervisningsaktivitet;
    return this;
  }

  

  /**
  * Get undervisningsaktivitet
  * @return undervisningsaktivitet
  **/
  @Schema(description = "")
  public Id2 getUndervisningsaktivitet() {
    return undervisningsaktivitet;
  }
  public void setUndervisningsaktivitet(Id2 undervisningsaktivitet) {
    this.undervisningsaktivitet = undervisningsaktivitet;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Personrolle personrolle = (Personrolle) o;
    return Objects.equals(this.id, personrolle.id) &&
        Objects.equals(this.rolle, personrolle.rolle) &&
        Objects.equals(this.periode, personrolle.periode) &&
        Objects.equals(this.studieprogram, personrolle.studieprogram) &&
        Objects.equals(this.evuKurs, personrolle.evuKurs) &&
        Objects.equals(this.undervisningsaktivitet, personrolle.undervisningsaktivitet);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, rolle, periode, studieprogram, evuKurs, undervisningsaktivitet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Personrolle {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rolle: ").append(toIndentedString(rolle)).append("\n");
    sb.append("    periode: ").append(toIndentedString(periode)).append("\n");
    sb.append("    studieprogram: ").append(toIndentedString(studieprogram)).append("\n");
    sb.append("    evuKurs: ").append(toIndentedString(evuKurs)).append("\n");
    sb.append("    undervisningsaktivitet: ").append(toIndentedString(undervisningsaktivitet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
