/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.RolleId;
import no.bibsys.fs.model.SprakFelter;

/**
 * Rolle
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Rolle {

  @JsonProperty("id")

  private RolleId id = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("publiseringsRollenavn")

  private String publiseringsRollenavn = null;

  @JsonProperty("lmsRollenavn")

  private String lmsRollenavn = null;

  @JsonProperty("langtLmsRollenavn")

  private String langtLmsRollenavn = null;

  @JsonProperty("publisering")

  private Boolean publisering = null;

  @JsonProperty("undervisning")

  private Boolean undervisning = null;

  @JsonProperty("aktiv")

  private Boolean aktiv = null;

  @JsonProperty("fagpersonWebTilgang")

  private Boolean fagpersonWebTilgang = null;

  @JsonProperty("imsRolle")

  private Integer imsRolle = null;

  @JsonProperty("felles")

  private Boolean felles = null;

  @JsonProperty("merknad")

  private String merknad = null;
  public Rolle id(RolleId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public RolleId getId() {
    return id;
  }
  public void setId(RolleId id) {
    this.id = id;
  }
  public Rolle navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public Rolle publiseringsRollenavn(String publiseringsRollenavn) {
    this.publiseringsRollenavn = publiseringsRollenavn;
    return this;
  }

  

  /**
  * Get publiseringsRollenavn
  * @return publiseringsRollenavn
  **/
  @Schema(description = "")
  public String getPubliseringsRollenavn() {
    return publiseringsRollenavn;
  }
  public void setPubliseringsRollenavn(String publiseringsRollenavn) {
    this.publiseringsRollenavn = publiseringsRollenavn;
  }
  public Rolle lmsRollenavn(String lmsRollenavn) {
    this.lmsRollenavn = lmsRollenavn;
    return this;
  }

  

  /**
  * Get lmsRollenavn
  * @return lmsRollenavn
  **/
  @Schema(description = "")
  public String getLmsRollenavn() {
    return lmsRollenavn;
  }
  public void setLmsRollenavn(String lmsRollenavn) {
    this.lmsRollenavn = lmsRollenavn;
  }
  public Rolle langtLmsRollenavn(String langtLmsRollenavn) {
    this.langtLmsRollenavn = langtLmsRollenavn;
    return this;
  }

  

  /**
  * Get langtLmsRollenavn
  * @return langtLmsRollenavn
  **/
  @Schema(description = "")
  public String getLangtLmsRollenavn() {
    return langtLmsRollenavn;
  }
  public void setLangtLmsRollenavn(String langtLmsRollenavn) {
    this.langtLmsRollenavn = langtLmsRollenavn;
  }
  public Rolle publisering(Boolean publisering) {
    this.publisering = publisering;
    return this;
  }

  

  /**
  * Get publisering
  * @return publisering
  **/
  @Schema(description = "")
  public Boolean isPublisering() {
    return publisering;
  }
  public void setPublisering(Boolean publisering) {
    this.publisering = publisering;
  }
  public Rolle undervisning(Boolean undervisning) {
    this.undervisning = undervisning;
    return this;
  }

  

  /**
  * Get undervisning
  * @return undervisning
  **/
  @Schema(description = "")
  public Boolean isUndervisning() {
    return undervisning;
  }
  public void setUndervisning(Boolean undervisning) {
    this.undervisning = undervisning;
  }
  public Rolle aktiv(Boolean aktiv) {
    this.aktiv = aktiv;
    return this;
  }

  

  /**
  * Get aktiv
  * @return aktiv
  **/
  @Schema(description = "")
  public Boolean isAktiv() {
    return aktiv;
  }
  public void setAktiv(Boolean aktiv) {
    this.aktiv = aktiv;
  }
  public Rolle fagpersonWebTilgang(Boolean fagpersonWebTilgang) {
    this.fagpersonWebTilgang = fagpersonWebTilgang;
    return this;
  }

  

  /**
  * Get fagpersonWebTilgang
  * @return fagpersonWebTilgang
  **/
  @Schema(description = "")
  public Boolean isFagpersonWebTilgang() {
    return fagpersonWebTilgang;
  }
  public void setFagpersonWebTilgang(Boolean fagpersonWebTilgang) {
    this.fagpersonWebTilgang = fagpersonWebTilgang;
  }
  public Rolle imsRolle(Integer imsRolle) {
    this.imsRolle = imsRolle;
    return this;
  }

  

  /**
  * Get imsRolle
  * @return imsRolle
  **/
  @Schema(description = "")
  public Integer getImsRolle() {
    return imsRolle;
  }
  public void setImsRolle(Integer imsRolle) {
    this.imsRolle = imsRolle;
  }
  public Rolle felles(Boolean felles) {
    this.felles = felles;
    return this;
  }

  

  /**
  * Get felles
  * @return felles
  **/
  @Schema(description = "")
  public Boolean isFelles() {
    return felles;
  }
  public void setFelles(Boolean felles) {
    this.felles = felles;
  }
  public Rolle merknad(String merknad) {
    this.merknad = merknad;
    return this;
  }

  

  /**
  * Get merknad
  * @return merknad
  **/
  @Schema(description = "")
  public String getMerknad() {
    return merknad;
  }
  public void setMerknad(String merknad) {
    this.merknad = merknad;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rolle rolle = (Rolle) o;
    return Objects.equals(this.id, rolle.id) &&
        Objects.equals(this.navn, rolle.navn) &&
        Objects.equals(this.publiseringsRollenavn, rolle.publiseringsRollenavn) &&
        Objects.equals(this.lmsRollenavn, rolle.lmsRollenavn) &&
        Objects.equals(this.langtLmsRollenavn, rolle.langtLmsRollenavn) &&
        Objects.equals(this.publisering, rolle.publisering) &&
        Objects.equals(this.undervisning, rolle.undervisning) &&
        Objects.equals(this.aktiv, rolle.aktiv) &&
        Objects.equals(this.fagpersonWebTilgang, rolle.fagpersonWebTilgang) &&
        Objects.equals(this.imsRolle, rolle.imsRolle) &&
        Objects.equals(this.felles, rolle.felles) &&
        Objects.equals(this.merknad, rolle.merknad);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, navn, publiseringsRollenavn, lmsRollenavn, langtLmsRollenavn, publisering, undervisning, aktiv, fagpersonWebTilgang, imsRolle, felles, merknad);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rolle {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    publiseringsRollenavn: ").append(toIndentedString(publiseringsRollenavn)).append("\n");
    sb.append("    lmsRollenavn: ").append(toIndentedString(lmsRollenavn)).append("\n");
    sb.append("    langtLmsRollenavn: ").append(toIndentedString(langtLmsRollenavn)).append("\n");
    sb.append("    publisering: ").append(toIndentedString(publisering)).append("\n");
    sb.append("    undervisning: ").append(toIndentedString(undervisning)).append("\n");
    sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
    sb.append("    fagpersonWebTilgang: ").append(toIndentedString(fagpersonWebTilgang)).append("\n");
    sb.append("    imsRolle: ").append(toIndentedString(imsRolle)).append("\n");
    sb.append("    felles: ").append(toIndentedString(felles)).append("\n");
    sb.append("    merknad: ").append(toIndentedString(merknad)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
