/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.DatoIntervaller;
import no.bibsys.fs.model.SemesterId;
import no.bibsys.fs.model.SprakFelter;
import no.bibsys.fs.model.VarighetInfo;

/**
 * Semester
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Semester {

  @JsonProperty("id")

  private SemesterId id = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("varighet")

  private VarighetInfo varighet = null;

  @JsonProperty("perioder")

  private DatoIntervaller perioder = null;

  @JsonProperty("startManed")

  private Integer startManed = null;

  @JsonProperty("startUke")

  private Integer startUke = null;

  @JsonProperty("aktiv")

  private Boolean aktiv = null;

  @JsonProperty("nsdSemester")

  private Integer nsdSemester = null;

  @JsonProperty("sorteringsnokkel")

  private Integer sorteringsnokkel = null;

  @JsonProperty("felles")

  private Boolean felles = null;
  public Semester id(SemesterId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public SemesterId getId() {
    return id;
  }
  public void setId(SemesterId id) {
    this.id = id;
  }
  public Semester navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public Semester varighet(VarighetInfo varighet) {
    this.varighet = varighet;
    return this;
  }

  

  /**
  * Get varighet
  * @return varighet
  **/
  @Schema(description = "")
  public VarighetInfo getVarighet() {
    return varighet;
  }
  public void setVarighet(VarighetInfo varighet) {
    this.varighet = varighet;
  }
  public Semester perioder(DatoIntervaller perioder) {
    this.perioder = perioder;
    return this;
  }

  

  /**
  * Get perioder
  * @return perioder
  **/
  @Schema(description = "")
  public DatoIntervaller getPerioder() {
    return perioder;
  }
  public void setPerioder(DatoIntervaller perioder) {
    this.perioder = perioder;
  }
  public Semester startManed(Integer startManed) {
    this.startManed = startManed;
    return this;
  }

  

  /**
  * Get startManed
  * @return startManed
  **/
  @Schema(description = "")
  public Integer getStartManed() {
    return startManed;
  }
  public void setStartManed(Integer startManed) {
    this.startManed = startManed;
  }
  public Semester startUke(Integer startUke) {
    this.startUke = startUke;
    return this;
  }

  

  /**
  * Get startUke
  * @return startUke
  **/
  @Schema(description = "")
  public Integer getStartUke() {
    return startUke;
  }
  public void setStartUke(Integer startUke) {
    this.startUke = startUke;
  }
  public Semester aktiv(Boolean aktiv) {
    this.aktiv = aktiv;
    return this;
  }

  

  /**
  * Get aktiv
  * @return aktiv
  **/
  @Schema(description = "")
  public Boolean isAktiv() {
    return aktiv;
  }
  public void setAktiv(Boolean aktiv) {
    this.aktiv = aktiv;
  }
  public Semester nsdSemester(Integer nsdSemester) {
    this.nsdSemester = nsdSemester;
    return this;
  }

  

  /**
  * Get nsdSemester
  * @return nsdSemester
  **/
  @Schema(description = "")
  public Integer getNsdSemester() {
    return nsdSemester;
  }
  public void setNsdSemester(Integer nsdSemester) {
    this.nsdSemester = nsdSemester;
  }
  public Semester sorteringsnokkel(Integer sorteringsnokkel) {
    this.sorteringsnokkel = sorteringsnokkel;
    return this;
  }

  

  /**
  * Get sorteringsnokkel
  * @return sorteringsnokkel
  **/
  @Schema(description = "")
  public Integer getSorteringsnokkel() {
    return sorteringsnokkel;
  }
  public void setSorteringsnokkel(Integer sorteringsnokkel) {
    this.sorteringsnokkel = sorteringsnokkel;
  }
  public Semester felles(Boolean felles) {
    this.felles = felles;
    return this;
  }

  

  /**
  * Get felles
  * @return felles
  **/
  @Schema(description = "")
  public Boolean isFelles() {
    return felles;
  }
  public void setFelles(Boolean felles) {
    this.felles = felles;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Semester semester = (Semester) o;
    return Objects.equals(this.id, semester.id) &&
        Objects.equals(this.navn, semester.navn) &&
        Objects.equals(this.varighet, semester.varighet) &&
        Objects.equals(this.perioder, semester.perioder) &&
        Objects.equals(this.startManed, semester.startManed) &&
        Objects.equals(this.startUke, semester.startUke) &&
        Objects.equals(this.aktiv, semester.aktiv) &&
        Objects.equals(this.nsdSemester, semester.nsdSemester) &&
        Objects.equals(this.sorteringsnokkel, semester.sorteringsnokkel) &&
        Objects.equals(this.felles, semester.felles);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, navn, varighet, perioder, startManed, startUke, aktiv, nsdSemester, sorteringsnokkel, felles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Semester {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    varighet: ").append(toIndentedString(varighet)).append("\n");
    sb.append("    perioder: ").append(toIndentedString(perioder)).append("\n");
    sb.append("    startManed: ").append(toIndentedString(startManed)).append("\n");
    sb.append("    startUke: ").append(toIndentedString(startUke)).append("\n");
    sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
    sb.append("    nsdSemester: ").append(toIndentedString(nsdSemester)).append("\n");
    sb.append("    sorteringsnokkel: ").append(toIndentedString(sorteringsnokkel)).append("\n");
    sb.append("    felles: ").append(toIndentedString(felles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
