/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.BegrStudierettStatusInfo;
import no.bibsys.fs.model.DatoIntervall;
import no.bibsys.fs.model.Id2;
import no.bibsys.fs.model.StudentStatusInfo;
import no.bibsys.fs.model.StudierettId;
import no.bibsys.fs.model.StudierettStatusInfo;

/**
 * Studierett
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Studierett {

  @JsonProperty("id")

  private StudierettId id = null;

  @JsonProperty("semester")

  private Id2 semester = null;

  @JsonProperty("periode")

  private DatoIntervall periode = null;

  @JsonProperty("privatist")

  private Boolean privatist = null;

  @JsonProperty("studentstatus")

  private StudentStatusInfo studentstatus = null;

  @JsonProperty("studierettstatus")

  private StudierettStatusInfo studierettstatus = null;

  @JsonProperty("begrensetStudierett")

  private BegrStudierettStatusInfo begrensetStudierett = null;

  @JsonProperty("studieniva")

  private Id2 studieniva = null;

  @JsonProperty("studieretning")

  private Id2 studieretning = null;
  public Studierett id(StudierettId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public StudierettId getId() {
    return id;
  }
  public void setId(StudierettId id) {
    this.id = id;
  }
  public Studierett semester(Id2 semester) {
    this.semester = semester;
    return this;
  }

  

  /**
  * Get semester
  * @return semester
  **/
  @Schema(description = "")
  public Id2 getSemester() {
    return semester;
  }
  public void setSemester(Id2 semester) {
    this.semester = semester;
  }
  public Studierett periode(DatoIntervall periode) {
    this.periode = periode;
    return this;
  }

  

  /**
  * Get periode
  * @return periode
  **/
  @Schema(description = "")
  public DatoIntervall getPeriode() {
    return periode;
  }
  public void setPeriode(DatoIntervall periode) {
    this.periode = periode;
  }
  public Studierett privatist(Boolean privatist) {
    this.privatist = privatist;
    return this;
  }

  

  /**
  * Get privatist
  * @return privatist
  **/
  @Schema(description = "")
  public Boolean isPrivatist() {
    return privatist;
  }
  public void setPrivatist(Boolean privatist) {
    this.privatist = privatist;
  }
  public Studierett studentstatus(StudentStatusInfo studentstatus) {
    this.studentstatus = studentstatus;
    return this;
  }

  

  /**
  * Get studentstatus
  * @return studentstatus
  **/
  @Schema(description = "")
  public StudentStatusInfo getStudentstatus() {
    return studentstatus;
  }
  public void setStudentstatus(StudentStatusInfo studentstatus) {
    this.studentstatus = studentstatus;
  }
  public Studierett studierettstatus(StudierettStatusInfo studierettstatus) {
    this.studierettstatus = studierettstatus;
    return this;
  }

  

  /**
  * Get studierettstatus
  * @return studierettstatus
  **/
  @Schema(description = "")
  public StudierettStatusInfo getStudierettstatus() {
    return studierettstatus;
  }
  public void setStudierettstatus(StudierettStatusInfo studierettstatus) {
    this.studierettstatus = studierettstatus;
  }
  public Studierett begrensetStudierett(BegrStudierettStatusInfo begrensetStudierett) {
    this.begrensetStudierett = begrensetStudierett;
    return this;
  }

  

  /**
  * Get begrensetStudierett
  * @return begrensetStudierett
  **/
  @Schema(description = "")
  public BegrStudierettStatusInfo getBegrensetStudierett() {
    return begrensetStudierett;
  }
  public void setBegrensetStudierett(BegrStudierettStatusInfo begrensetStudierett) {
    this.begrensetStudierett = begrensetStudierett;
  }
  public Studierett studieniva(Id2 studieniva) {
    this.studieniva = studieniva;
    return this;
  }

  

  /**
  * Get studieniva
  * @return studieniva
  **/
  @Schema(description = "")
  public Id2 getStudieniva() {
    return studieniva;
  }
  public void setStudieniva(Id2 studieniva) {
    this.studieniva = studieniva;
  }
  public Studierett studieretning(Id2 studieretning) {
    this.studieretning = studieretning;
    return this;
  }

  

  /**
  * Get studieretning
  * @return studieretning
  **/
  @Schema(description = "")
  public Id2 getStudieretning() {
    return studieretning;
  }
  public void setStudieretning(Id2 studieretning) {
    this.studieretning = studieretning;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Studierett studierett = (Studierett) o;
    return Objects.equals(this.id, studierett.id) &&
        Objects.equals(this.semester, studierett.semester) &&
        Objects.equals(this.periode, studierett.periode) &&
        Objects.equals(this.privatist, studierett.privatist) &&
        Objects.equals(this.studentstatus, studierett.studentstatus) &&
        Objects.equals(this.studierettstatus, studierett.studierettstatus) &&
        Objects.equals(this.begrensetStudierett, studierett.begrensetStudierett) &&
        Objects.equals(this.studieniva, studierett.studieniva) &&
        Objects.equals(this.studieretning, studierett.studieretning);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, semester, periode, privatist, studentstatus, studierettstatus, begrensetStudierett, studieniva, studieretning);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Studierett {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    semester: ").append(toIndentedString(semester)).append("\n");
    sb.append("    periode: ").append(toIndentedString(periode)).append("\n");
    sb.append("    privatist: ").append(toIndentedString(privatist)).append("\n");
    sb.append("    studentstatus: ").append(toIndentedString(studentstatus)).append("\n");
    sb.append("    studierettstatus: ").append(toIndentedString(studierettstatus)).append("\n");
    sb.append("    begrensetStudierett: ").append(toIndentedString(begrensetStudierett)).append("\n");
    sb.append("    studieniva: ").append(toIndentedString(studieniva)).append("\n");
    sb.append("    studieretning: ").append(toIndentedString(studieretning)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
