/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.Id2;
import no.bibsys.fs.model.SprakFelter;
import no.bibsys.fs.model.StudieretningId;

/**
 * Studieretning
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Studieretning {

  @JsonProperty("id")

  private StudieretningId id = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("fag")

  private Id2 fag = null;

  @JsonProperty("aktiv")

  private Boolean aktiv = null;

  @JsonProperty("betegnelse")

  private String betegnelse = null;
  public Studieretning id(StudieretningId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public StudieretningId getId() {
    return id;
  }
  public void setId(StudieretningId id) {
    this.id = id;
  }
  public Studieretning navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public Studieretning fag(Id2 fag) {
    this.fag = fag;
    return this;
  }

  

  /**
  * Get fag
  * @return fag
  **/
  @Schema(description = "")
  public Id2 getFag() {
    return fag;
  }
  public void setFag(Id2 fag) {
    this.fag = fag;
  }
  public Studieretning aktiv(Boolean aktiv) {
    this.aktiv = aktiv;
    return this;
  }

  

  /**
  * Get aktiv
  * @return aktiv
  **/
  @Schema(description = "")
  public Boolean isAktiv() {
    return aktiv;
  }
  public void setAktiv(Boolean aktiv) {
    this.aktiv = aktiv;
  }
  public Studieretning betegnelse(String betegnelse) {
    this.betegnelse = betegnelse;
    return this;
  }

  

  /**
  * Get betegnelse
  * @return betegnelse
  **/
  @Schema(description = "")
  public String getBetegnelse() {
    return betegnelse;
  }
  public void setBetegnelse(String betegnelse) {
    this.betegnelse = betegnelse;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Studieretning studieretning = (Studieretning) o;
    return Objects.equals(this.id, studieretning.id) &&
        Objects.equals(this.navn, studieretning.navn) &&
        Objects.equals(this.fag, studieretning.fag) &&
        Objects.equals(this.aktiv, studieretning.aktiv) &&
        Objects.equals(this.betegnelse, studieretning.betegnelse);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, navn, fag, aktiv, betegnelse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Studieretning {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    fag: ").append(toIndentedString(fag)).append("\n");
    sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
    sb.append("    betegnelse: ").append(toIndentedString(betegnelse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
