/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.ErasmusNivaInfo;
import no.bibsys.fs.model.NKRSyklusInfo;
import no.bibsys.fs.model.SprakFelter;
import no.bibsys.fs.model.StudienivaId;
import no.bibsys.fs.model.StudienivaStudienivaIntervall;

/**
 * Studieniva
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Studieniva {

  @JsonProperty("id")

  private StudienivaId id = null;

  @JsonProperty("studienivanavn")

  private SprakFelter studienivanavn = null;

  @JsonProperty("studienivaIntervall")

  private StudienivaStudienivaIntervall studienivaIntervall = null;

  @JsonProperty("nsdNivakode")

  private String nsdNivakode = null;

  @JsonProperty("felles")

  private Boolean felles = null;

  @JsonProperty("erasmusniva")

  private ErasmusNivaInfo erasmusniva = null;

  @JsonProperty("emne")

  private Boolean emne = null;

  @JsonProperty("studieprogram")

  private Boolean studieprogram = null;

  @JsonProperty("kvalifikasjon")

  private Boolean kvalifikasjon = null;

  @JsonProperty("videreutdanning")

  private Boolean videreutdanning = null;

  @JsonProperty("nkrSyklus")

  private NKRSyklusInfo nkrSyklus = null;
  public Studieniva id(StudienivaId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public StudienivaId getId() {
    return id;
  }
  public void setId(StudienivaId id) {
    this.id = id;
  }
  public Studieniva studienivanavn(SprakFelter studienivanavn) {
    this.studienivanavn = studienivanavn;
    return this;
  }

  

  /**
  * Get studienivanavn
  * @return studienivanavn
  **/
  @Schema(description = "")
  public SprakFelter getStudienivanavn() {
    return studienivanavn;
  }
  public void setStudienivanavn(SprakFelter studienivanavn) {
    this.studienivanavn = studienivanavn;
  }
  public Studieniva studienivaIntervall(StudienivaStudienivaIntervall studienivaIntervall) {
    this.studienivaIntervall = studienivaIntervall;
    return this;
  }

  

  /**
  * Get studienivaIntervall
  * @return studienivaIntervall
  **/
  @Schema(description = "")
  public StudienivaStudienivaIntervall getStudienivaIntervall() {
    return studienivaIntervall;
  }
  public void setStudienivaIntervall(StudienivaStudienivaIntervall studienivaIntervall) {
    this.studienivaIntervall = studienivaIntervall;
  }
  public Studieniva nsdNivakode(String nsdNivakode) {
    this.nsdNivakode = nsdNivakode;
    return this;
  }

  

  /**
  * Get nsdNivakode
  * @return nsdNivakode
  **/
  @Schema(description = "")
  public String getNsdNivakode() {
    return nsdNivakode;
  }
  public void setNsdNivakode(String nsdNivakode) {
    this.nsdNivakode = nsdNivakode;
  }
  public Studieniva felles(Boolean felles) {
    this.felles = felles;
    return this;
  }

  

  /**
  * Get felles
  * @return felles
  **/
  @Schema(description = "")
  public Boolean isFelles() {
    return felles;
  }
  public void setFelles(Boolean felles) {
    this.felles = felles;
  }
  public Studieniva erasmusniva(ErasmusNivaInfo erasmusniva) {
    this.erasmusniva = erasmusniva;
    return this;
  }

  

  /**
  * Get erasmusniva
  * @return erasmusniva
  **/
  @Schema(description = "")
  public ErasmusNivaInfo getErasmusniva() {
    return erasmusniva;
  }
  public void setErasmusniva(ErasmusNivaInfo erasmusniva) {
    this.erasmusniva = erasmusniva;
  }
  public Studieniva emne(Boolean emne) {
    this.emne = emne;
    return this;
  }

  

  /**
  * Get emne
  * @return emne
  **/
  @Schema(description = "")
  public Boolean isEmne() {
    return emne;
  }
  public void setEmne(Boolean emne) {
    this.emne = emne;
  }
  public Studieniva studieprogram(Boolean studieprogram) {
    this.studieprogram = studieprogram;
    return this;
  }

  

  /**
  * Get studieprogram
  * @return studieprogram
  **/
  @Schema(description = "")
  public Boolean isStudieprogram() {
    return studieprogram;
  }
  public void setStudieprogram(Boolean studieprogram) {
    this.studieprogram = studieprogram;
  }
  public Studieniva kvalifikasjon(Boolean kvalifikasjon) {
    this.kvalifikasjon = kvalifikasjon;
    return this;
  }

  

  /**
  * Get kvalifikasjon
  * @return kvalifikasjon
  **/
  @Schema(description = "")
  public Boolean isKvalifikasjon() {
    return kvalifikasjon;
  }
  public void setKvalifikasjon(Boolean kvalifikasjon) {
    this.kvalifikasjon = kvalifikasjon;
  }
  public Studieniva videreutdanning(Boolean videreutdanning) {
    this.videreutdanning = videreutdanning;
    return this;
  }

  

  /**
  * Get videreutdanning
  * @return videreutdanning
  **/
  @Schema(description = "")
  public Boolean isVidereutdanning() {
    return videreutdanning;
  }
  public void setVidereutdanning(Boolean videreutdanning) {
    this.videreutdanning = videreutdanning;
  }
  public Studieniva nkrSyklus(NKRSyklusInfo nkrSyklus) {
    this.nkrSyklus = nkrSyklus;
    return this;
  }

  

  /**
  * Get nkrSyklus
  * @return nkrSyklus
  **/
  @Schema(description = "")
  public NKRSyklusInfo getNkrSyklus() {
    return nkrSyklus;
  }
  public void setNkrSyklus(NKRSyklusInfo nkrSyklus) {
    this.nkrSyklus = nkrSyklus;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Studieniva studieniva = (Studieniva) o;
    return Objects.equals(this.id, studieniva.id) &&
        Objects.equals(this.studienivanavn, studieniva.studienivanavn) &&
        Objects.equals(this.studienivaIntervall, studieniva.studienivaIntervall) &&
        Objects.equals(this.nsdNivakode, studieniva.nsdNivakode) &&
        Objects.equals(this.felles, studieniva.felles) &&
        Objects.equals(this.erasmusniva, studieniva.erasmusniva) &&
        Objects.equals(this.emne, studieniva.emne) &&
        Objects.equals(this.studieprogram, studieniva.studieprogram) &&
        Objects.equals(this.kvalifikasjon, studieniva.kvalifikasjon) &&
        Objects.equals(this.videreutdanning, studieniva.videreutdanning) &&
        Objects.equals(this.nkrSyklus, studieniva.nkrSyklus);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, studienivanavn, studienivaIntervall, nsdNivakode, felles, erasmusniva, emne, studieprogram, kvalifikasjon, videreutdanning, nkrSyklus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Studieniva {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    studienivanavn: ").append(toIndentedString(studienivanavn)).append("\n");
    sb.append("    studienivaIntervall: ").append(toIndentedString(studienivaIntervall)).append("\n");
    sb.append("    nsdNivakode: ").append(toIndentedString(nsdNivakode)).append("\n");
    sb.append("    felles: ").append(toIndentedString(felles)).append("\n");
    sb.append("    erasmusniva: ").append(toIndentedString(erasmusniva)).append("\n");
    sb.append("    emne: ").append(toIndentedString(emne)).append("\n");
    sb.append("    studieprogram: ").append(toIndentedString(studieprogram)).append("\n");
    sb.append("    kvalifikasjon: ").append(toIndentedString(kvalifikasjon)).append("\n");
    sb.append("    videreutdanning: ").append(toIndentedString(videreutdanning)).append("\n");
    sb.append("    nkrSyklus: ").append(toIndentedString(nkrSyklus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
