/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.Id2;
import no.bibsys.fs.model.StudentUndervisningId;

/**
 * StudentUndervisning
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class StudentUndervisning {

  @JsonProperty("id")

  private StudentUndervisningId id = null;

  @JsonProperty("semester")

  private Id2 semester = null;

  @JsonProperty("prioritet")

  private Integer prioritet = null;

  @JsonProperty("kvalifisert")

  private Boolean kvalifisert = null;

  @JsonProperty("betingetKvalifisert")

  private Boolean betingetKvalifisert = null;

  @JsonProperty("svarPaTilbud")

  private Boolean svarPaTilbud = null;

  @JsonProperty("fremmote")

  private Boolean fremmote = null;

  @JsonProperty("publiserOpptak")

  private Boolean publiserOpptak = null;

  @JsonProperty("opptatt")

  private Boolean opptatt = null;

  @JsonProperty("tilbudstatus")

  private Id2 tilbudstatus = null;

  @JsonProperty("ventelistenummer")

  private Integer ventelistenummer = null;

  @JsonProperty("pameldingsrekkefolge")

  private Integer pameldingsrekkefolge = null;

  @JsonProperty("loddtrekningsnummer")

  private Integer loddtrekningsnummer = null;
  public StudentUndervisning id(StudentUndervisningId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public StudentUndervisningId getId() {
    return id;
  }
  public void setId(StudentUndervisningId id) {
    this.id = id;
  }
  public StudentUndervisning semester(Id2 semester) {
    this.semester = semester;
    return this;
  }

  

  /**
  * Get semester
  * @return semester
  **/
  @Schema(description = "")
  public Id2 getSemester() {
    return semester;
  }
  public void setSemester(Id2 semester) {
    this.semester = semester;
  }
  public StudentUndervisning prioritet(Integer prioritet) {
    this.prioritet = prioritet;
    return this;
  }

  

  /**
  * Get prioritet
  * @return prioritet
  **/
  @Schema(description = "")
  public Integer getPrioritet() {
    return prioritet;
  }
  public void setPrioritet(Integer prioritet) {
    this.prioritet = prioritet;
  }
  public StudentUndervisning kvalifisert(Boolean kvalifisert) {
    this.kvalifisert = kvalifisert;
    return this;
  }

  

  /**
  * Get kvalifisert
  * @return kvalifisert
  **/
  @Schema(description = "")
  public Boolean isKvalifisert() {
    return kvalifisert;
  }
  public void setKvalifisert(Boolean kvalifisert) {
    this.kvalifisert = kvalifisert;
  }
  public StudentUndervisning betingetKvalifisert(Boolean betingetKvalifisert) {
    this.betingetKvalifisert = betingetKvalifisert;
    return this;
  }

  

  /**
  * Get betingetKvalifisert
  * @return betingetKvalifisert
  **/
  @Schema(description = "")
  public Boolean isBetingetKvalifisert() {
    return betingetKvalifisert;
  }
  public void setBetingetKvalifisert(Boolean betingetKvalifisert) {
    this.betingetKvalifisert = betingetKvalifisert;
  }
  public StudentUndervisning svarPaTilbud(Boolean svarPaTilbud) {
    this.svarPaTilbud = svarPaTilbud;
    return this;
  }

  

  /**
  * Get svarPaTilbud
  * @return svarPaTilbud
  **/
  @Schema(description = "")
  public Boolean isSvarPaTilbud() {
    return svarPaTilbud;
  }
  public void setSvarPaTilbud(Boolean svarPaTilbud) {
    this.svarPaTilbud = svarPaTilbud;
  }
  public StudentUndervisning fremmote(Boolean fremmote) {
    this.fremmote = fremmote;
    return this;
  }

  

  /**
  * Get fremmote
  * @return fremmote
  **/
  @Schema(description = "")
  public Boolean isFremmote() {
    return fremmote;
  }
  public void setFremmote(Boolean fremmote) {
    this.fremmote = fremmote;
  }
  public StudentUndervisning publiserOpptak(Boolean publiserOpptak) {
    this.publiserOpptak = publiserOpptak;
    return this;
  }

  

  /**
  * Get publiserOpptak
  * @return publiserOpptak
  **/
  @Schema(description = "")
  public Boolean isPubliserOpptak() {
    return publiserOpptak;
  }
  public void setPubliserOpptak(Boolean publiserOpptak) {
    this.publiserOpptak = publiserOpptak;
  }
  public StudentUndervisning opptatt(Boolean opptatt) {
    this.opptatt = opptatt;
    return this;
  }

  

  /**
  * Get opptatt
  * @return opptatt
  **/
  @Schema(description = "")
  public Boolean isOpptatt() {
    return opptatt;
  }
  public void setOpptatt(Boolean opptatt) {
    this.opptatt = opptatt;
  }
  public StudentUndervisning tilbudstatus(Id2 tilbudstatus) {
    this.tilbudstatus = tilbudstatus;
    return this;
  }

  

  /**
  * Get tilbudstatus
  * @return tilbudstatus
  **/
  @Schema(description = "")
  public Id2 getTilbudstatus() {
    return tilbudstatus;
  }
  public void setTilbudstatus(Id2 tilbudstatus) {
    this.tilbudstatus = tilbudstatus;
  }
  public StudentUndervisning ventelistenummer(Integer ventelistenummer) {
    this.ventelistenummer = ventelistenummer;
    return this;
  }

  

  /**
  * Get ventelistenummer
  * @return ventelistenummer
  **/
  @Schema(description = "")
  public Integer getVentelistenummer() {
    return ventelistenummer;
  }
  public void setVentelistenummer(Integer ventelistenummer) {
    this.ventelistenummer = ventelistenummer;
  }
  public StudentUndervisning pameldingsrekkefolge(Integer pameldingsrekkefolge) {
    this.pameldingsrekkefolge = pameldingsrekkefolge;
    return this;
  }

  

  /**
  * Get pameldingsrekkefolge
  * @return pameldingsrekkefolge
  **/
  @Schema(description = "")
  public Integer getPameldingsrekkefolge() {
    return pameldingsrekkefolge;
  }
  public void setPameldingsrekkefolge(Integer pameldingsrekkefolge) {
    this.pameldingsrekkefolge = pameldingsrekkefolge;
  }
  public StudentUndervisning loddtrekningsnummer(Integer loddtrekningsnummer) {
    this.loddtrekningsnummer = loddtrekningsnummer;
    return this;
  }

  

  /**
  * Get loddtrekningsnummer
  * @return loddtrekningsnummer
  **/
  @Schema(description = "")
  public Integer getLoddtrekningsnummer() {
    return loddtrekningsnummer;
  }
  public void setLoddtrekningsnummer(Integer loddtrekningsnummer) {
    this.loddtrekningsnummer = loddtrekningsnummer;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentUndervisning studentUndervisning = (StudentUndervisning) o;
    return Objects.equals(this.id, studentUndervisning.id) &&
        Objects.equals(this.semester, studentUndervisning.semester) &&
        Objects.equals(this.prioritet, studentUndervisning.prioritet) &&
        Objects.equals(this.kvalifisert, studentUndervisning.kvalifisert) &&
        Objects.equals(this.betingetKvalifisert, studentUndervisning.betingetKvalifisert) &&
        Objects.equals(this.svarPaTilbud, studentUndervisning.svarPaTilbud) &&
        Objects.equals(this.fremmote, studentUndervisning.fremmote) &&
        Objects.equals(this.publiserOpptak, studentUndervisning.publiserOpptak) &&
        Objects.equals(this.opptatt, studentUndervisning.opptatt) &&
        Objects.equals(this.tilbudstatus, studentUndervisning.tilbudstatus) &&
        Objects.equals(this.ventelistenummer, studentUndervisning.ventelistenummer) &&
        Objects.equals(this.pameldingsrekkefolge, studentUndervisning.pameldingsrekkefolge) &&
        Objects.equals(this.loddtrekningsnummer, studentUndervisning.loddtrekningsnummer);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, semester, prioritet, kvalifisert, betingetKvalifisert, svarPaTilbud, fremmote, publiserOpptak, opptatt, tilbudstatus, ventelistenummer, pameldingsrekkefolge, loddtrekningsnummer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentUndervisning {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    semester: ").append(toIndentedString(semester)).append("\n");
    sb.append("    prioritet: ").append(toIndentedString(prioritet)).append("\n");
    sb.append("    kvalifisert: ").append(toIndentedString(kvalifisert)).append("\n");
    sb.append("    betingetKvalifisert: ").append(toIndentedString(betingetKvalifisert)).append("\n");
    sb.append("    svarPaTilbud: ").append(toIndentedString(svarPaTilbud)).append("\n");
    sb.append("    fremmote: ").append(toIndentedString(fremmote)).append("\n");
    sb.append("    publiserOpptak: ").append(toIndentedString(publiserOpptak)).append("\n");
    sb.append("    opptatt: ").append(toIndentedString(opptatt)).append("\n");
    sb.append("    tilbudstatus: ").append(toIndentedString(tilbudstatus)).append("\n");
    sb.append("    ventelistenummer: ").append(toIndentedString(ventelistenummer)).append("\n");
    sb.append("    pameldingsrekkefolge: ").append(toIndentedString(pameldingsrekkefolge)).append("\n");
    sb.append("    loddtrekningsnummer: ").append(toIndentedString(loddtrekningsnummer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
