/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.SprakFelter;

/**
 * StudentStatusInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class StudentStatusInfo {

  @JsonProperty("kode")

  private String kode = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("sperrUtdanningsplan")

  private Boolean sperrUtdanningsplan = null;

  @JsonProperty("aktivStudent")

  private Boolean aktivStudent = null;

  @JsonProperty("visUtdanningsplan")

  private Boolean visUtdanningsplan = null;

  @JsonProperty("felles")

  private Boolean felles = null;
  public StudentStatusInfo kode(String kode) {
    this.kode = kode;
    return this;
  }

  

  /**
  * Get kode
  * @return kode
  **/
  @Schema(description = "")
  public String getKode() {
    return kode;
  }
  public void setKode(String kode) {
    this.kode = kode;
  }
  public StudentStatusInfo navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public StudentStatusInfo sperrUtdanningsplan(Boolean sperrUtdanningsplan) {
    this.sperrUtdanningsplan = sperrUtdanningsplan;
    return this;
  }

  

  /**
  * Get sperrUtdanningsplan
  * @return sperrUtdanningsplan
  **/
  @Schema(description = "")
  public Boolean isSperrUtdanningsplan() {
    return sperrUtdanningsplan;
  }
  public void setSperrUtdanningsplan(Boolean sperrUtdanningsplan) {
    this.sperrUtdanningsplan = sperrUtdanningsplan;
  }
  public StudentStatusInfo aktivStudent(Boolean aktivStudent) {
    this.aktivStudent = aktivStudent;
    return this;
  }

  

  /**
  * Get aktivStudent
  * @return aktivStudent
  **/
  @Schema(description = "")
  public Boolean isAktivStudent() {
    return aktivStudent;
  }
  public void setAktivStudent(Boolean aktivStudent) {
    this.aktivStudent = aktivStudent;
  }
  public StudentStatusInfo visUtdanningsplan(Boolean visUtdanningsplan) {
    this.visUtdanningsplan = visUtdanningsplan;
    return this;
  }

  

  /**
  * Get visUtdanningsplan
  * @return visUtdanningsplan
  **/
  @Schema(description = "")
  public Boolean isVisUtdanningsplan() {
    return visUtdanningsplan;
  }
  public void setVisUtdanningsplan(Boolean visUtdanningsplan) {
    this.visUtdanningsplan = visUtdanningsplan;
  }
  public StudentStatusInfo felles(Boolean felles) {
    this.felles = felles;
    return this;
  }

  

  /**
  * Get felles
  * @return felles
  **/
  @Schema(description = "")
  public Boolean isFelles() {
    return felles;
  }
  public void setFelles(Boolean felles) {
    this.felles = felles;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentStatusInfo studentStatusInfo = (StudentStatusInfo) o;
    return Objects.equals(this.kode, studentStatusInfo.kode) &&
        Objects.equals(this.navn, studentStatusInfo.navn) &&
        Objects.equals(this.sperrUtdanningsplan, studentStatusInfo.sperrUtdanningsplan) &&
        Objects.equals(this.aktivStudent, studentStatusInfo.aktivStudent) &&
        Objects.equals(this.visUtdanningsplan, studentStatusInfo.visUtdanningsplan) &&
        Objects.equals(this.felles, studentStatusInfo.felles);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(kode, navn, sperrUtdanningsplan, aktivStudent, visUtdanningsplan, felles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentStatusInfo {\n");
    
    sb.append("    kode: ").append(toIndentedString(kode)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    sperrUtdanningsplan: ").append(toIndentedString(sperrUtdanningsplan)).append("\n");
    sb.append("    aktivStudent: ").append(toIndentedString(aktivStudent)).append("\n");
    sb.append("    visUtdanningsplan: ").append(toIndentedString(visUtdanningsplan)).append("\n");
    sb.append("    felles: ").append(toIndentedString(felles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
