/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.Id2;

/**
 * StudentUndervisningsAktivitetId
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class StudentUndervisningsAktivitetId {

  @JsonProperty("href")

  private String href = null;
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    EMPTY("");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }
  @JsonProperty("type")

  private TypeEnum type = null;

  @JsonProperty("person")

  private Id2 person = null;

  @JsonProperty("undervisningsaktivitet")

  private Id2 undervisningsaktivitet = null;

  @JsonProperty("parti")

  private Integer parti = null;

  @JsonProperty("form")

  private String form = null;

  @JsonProperty("disiplin")

  private String disiplin = null;
  public StudentUndervisningsAktivitetId href(String href) {
    this.href = href;
    return this;
  }

  

  /**
  * Get href
  * @return href
  **/
  @Schema(example = "https://server/studentundervisningsaktiviteter/id", description = "")
  public String getHref() {
    return href;
  }
  public void setHref(String href) {
    this.href = href;
  }
  public StudentUndervisningsAktivitetId type(TypeEnum type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }
  public void setType(TypeEnum type) {
    this.type = type;
  }
  public StudentUndervisningsAktivitetId person(Id2 person) {
    this.person = person;
    return this;
  }

  

  /**
  * Get person
  * @return person
  **/
  @Schema(description = "")
  public Id2 getPerson() {
    return person;
  }
  public void setPerson(Id2 person) {
    this.person = person;
  }
  public StudentUndervisningsAktivitetId undervisningsaktivitet(Id2 undervisningsaktivitet) {
    this.undervisningsaktivitet = undervisningsaktivitet;
    return this;
  }

  

  /**
  * Get undervisningsaktivitet
  * @return undervisningsaktivitet
  **/
  @Schema(description = "")
  public Id2 getUndervisningsaktivitet() {
    return undervisningsaktivitet;
  }
  public void setUndervisningsaktivitet(Id2 undervisningsaktivitet) {
    this.undervisningsaktivitet = undervisningsaktivitet;
  }
  public StudentUndervisningsAktivitetId parti(Integer parti) {
    this.parti = parti;
    return this;
  }

  

  /**
  * Get parti
  * @return parti
  **/
  @Schema(description = "")
  public Integer getParti() {
    return parti;
  }
  public void setParti(Integer parti) {
    this.parti = parti;
  }
  public StudentUndervisningsAktivitetId form(String form) {
    this.form = form;
    return this;
  }

  

  /**
  * Get form
  * @return form
  **/
  @Schema(description = "")
  public String getForm() {
    return form;
  }
  public void setForm(String form) {
    this.form = form;
  }
  public StudentUndervisningsAktivitetId disiplin(String disiplin) {
    this.disiplin = disiplin;
    return this;
  }

  

  /**
  * Get disiplin
  * @return disiplin
  **/
  @Schema(description = "")
  public String getDisiplin() {
    return disiplin;
  }
  public void setDisiplin(String disiplin) {
    this.disiplin = disiplin;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentUndervisningsAktivitetId studentUndervisningsAktivitetId = (StudentUndervisningsAktivitetId) o;
    return Objects.equals(this.href, studentUndervisningsAktivitetId.href) &&
        Objects.equals(this.type, studentUndervisningsAktivitetId.type) &&
        Objects.equals(this.person, studentUndervisningsAktivitetId.person) &&
        Objects.equals(this.undervisningsaktivitet, studentUndervisningsAktivitetId.undervisningsaktivitet) &&
        Objects.equals(this.parti, studentUndervisningsAktivitetId.parti) &&
        Objects.equals(this.form, studentUndervisningsAktivitetId.form) &&
        Objects.equals(this.disiplin, studentUndervisningsAktivitetId.disiplin);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(href, type, person, undervisningsaktivitet, parti, form, disiplin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentUndervisningsAktivitetId {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    undervisningsaktivitet: ").append(toIndentedString(undervisningsaktivitet)).append("\n");
    sb.append("    parti: ").append(toIndentedString(parti)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    disiplin: ").append(toIndentedString(disiplin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
