/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * StudentInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class StudentInfo {

  @JsonProperty("studentnummer")

  private Integer studentnummer = null;
  public StudentInfo studentnummer(Integer studentnummer) {
    this.studentnummer = studentnummer;
    return this;
  }

  

  /**
  * Get studentnummer
  * maximum: 999999
  * @return studentnummer
  **/
  @Schema(description = "")
  public Integer getStudentnummer() {
    return studentnummer;
  }
  public void setStudentnummer(Integer studentnummer) {
    this.studentnummer = studentnummer;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentInfo studentInfo = (StudentInfo) o;
    return Objects.equals(this.studentnummer, studentInfo.studentnummer);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(studentnummer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentInfo {\n");
    
    sb.append("    studentnummer: ").append(toIndentedString(studentnummer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
