/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.StudentUndervisningsAktivitetId;

/**
 * StudentUndervisningsAktivitet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class StudentUndervisningsAktivitet {

  @JsonProperty("id")

  private StudentUndervisningsAktivitetId id = null;

  @JsonProperty("prioritet")

  private Integer prioritet = null;

  @JsonProperty("tildelt")

  private Boolean tildelt = null;

  @JsonProperty("laSta")

  private Boolean laSta = null;

  @JsonProperty("spesialtilbud")

  private Boolean spesialtilbud = null;

  @JsonProperty("sperrSletting")

  private Boolean sperrSletting = null;
  public StudentUndervisningsAktivitet id(StudentUndervisningsAktivitetId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public StudentUndervisningsAktivitetId getId() {
    return id;
  }
  public void setId(StudentUndervisningsAktivitetId id) {
    this.id = id;
  }
  public StudentUndervisningsAktivitet prioritet(Integer prioritet) {
    this.prioritet = prioritet;
    return this;
  }

  

  /**
  * Get prioritet
  * @return prioritet
  **/
  @Schema(description = "")
  public Integer getPrioritet() {
    return prioritet;
  }
  public void setPrioritet(Integer prioritet) {
    this.prioritet = prioritet;
  }
  public StudentUndervisningsAktivitet tildelt(Boolean tildelt) {
    this.tildelt = tildelt;
    return this;
  }

  

  /**
  * Get tildelt
  * @return tildelt
  **/
  @Schema(description = "")
  public Boolean isTildelt() {
    return tildelt;
  }
  public void setTildelt(Boolean tildelt) {
    this.tildelt = tildelt;
  }
  public StudentUndervisningsAktivitet laSta(Boolean laSta) {
    this.laSta = laSta;
    return this;
  }

  

  /**
  * Get laSta
  * @return laSta
  **/
  @Schema(description = "")
  public Boolean isLaSta() {
    return laSta;
  }
  public void setLaSta(Boolean laSta) {
    this.laSta = laSta;
  }
  public StudentUndervisningsAktivitet spesialtilbud(Boolean spesialtilbud) {
    this.spesialtilbud = spesialtilbud;
    return this;
  }

  

  /**
  * Get spesialtilbud
  * @return spesialtilbud
  **/
  @Schema(description = "")
  public Boolean isSpesialtilbud() {
    return spesialtilbud;
  }
  public void setSpesialtilbud(Boolean spesialtilbud) {
    this.spesialtilbud = spesialtilbud;
  }
  public StudentUndervisningsAktivitet sperrSletting(Boolean sperrSletting) {
    this.sperrSletting = sperrSletting;
    return this;
  }

  

  /**
  * Get sperrSletting
  * @return sperrSletting
  **/
  @Schema(description = "")
  public Boolean isSperrSletting() {
    return sperrSletting;
  }
  public void setSperrSletting(Boolean sperrSletting) {
    this.sperrSletting = sperrSletting;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentUndervisningsAktivitet studentUndervisningsAktivitet = (StudentUndervisningsAktivitet) o;
    return Objects.equals(this.id, studentUndervisningsAktivitet.id) &&
        Objects.equals(this.prioritet, studentUndervisningsAktivitet.prioritet) &&
        Objects.equals(this.tildelt, studentUndervisningsAktivitet.tildelt) &&
        Objects.equals(this.laSta, studentUndervisningsAktivitet.laSta) &&
        Objects.equals(this.spesialtilbud, studentUndervisningsAktivitet.spesialtilbud) &&
        Objects.equals(this.sperrSletting, studentUndervisningsAktivitet.sperrSletting);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, prioritet, tildelt, laSta, spesialtilbud, sperrSletting);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentUndervisningsAktivitet {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    prioritet: ").append(toIndentedString(prioritet)).append("\n");
    sb.append("    tildelt: ").append(toIndentedString(tildelt)).append("\n");
    sb.append("    laSta: ").append(toIndentedString(laSta)).append("\n");
    sb.append("    spesialtilbud: ").append(toIndentedString(spesialtilbud)).append("\n");
    sb.append("    sperrSletting: ").append(toIndentedString(sperrSletting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
