/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.SprakFelter;

/**
 * TidsenhetInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class TidsenhetInfo {

  @JsonProperty("kode")

  private String kode = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("aktiv")

  private Boolean aktiv = null;

  @JsonProperty("rekkefolgenummer")

  private Integer rekkefolgenummer = null;
  public TidsenhetInfo kode(String kode) {
    this.kode = kode;
    return this;
  }

  

  /**
  * Get kode
  * @return kode
  **/
  @Schema(description = "")
  public String getKode() {
    return kode;
  }
  public void setKode(String kode) {
    this.kode = kode;
  }
  public TidsenhetInfo navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public TidsenhetInfo aktiv(Boolean aktiv) {
    this.aktiv = aktiv;
    return this;
  }

  

  /**
  * Get aktiv
  * @return aktiv
  **/
  @Schema(description = "")
  public Boolean isAktiv() {
    return aktiv;
  }
  public void setAktiv(Boolean aktiv) {
    this.aktiv = aktiv;
  }
  public TidsenhetInfo rekkefolgenummer(Integer rekkefolgenummer) {
    this.rekkefolgenummer = rekkefolgenummer;
    return this;
  }

  

  /**
  * Get rekkefolgenummer
  * @return rekkefolgenummer
  **/
  @Schema(description = "")
  public Integer getRekkefolgenummer() {
    return rekkefolgenummer;
  }
  public void setRekkefolgenummer(Integer rekkefolgenummer) {
    this.rekkefolgenummer = rekkefolgenummer;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TidsenhetInfo tidsenhetInfo = (TidsenhetInfo) o;
    return Objects.equals(this.kode, tidsenhetInfo.kode) &&
        Objects.equals(this.navn, tidsenhetInfo.navn) &&
        Objects.equals(this.aktiv, tidsenhetInfo.aktiv) &&
        Objects.equals(this.rekkefolgenummer, tidsenhetInfo.rekkefolgenummer);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(kode, navn, aktiv, rekkefolgenummer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TidsenhetInfo {\n");
    
    sb.append("    kode: ").append(toIndentedString(kode)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
    sb.append("    rekkefolgenummer: ").append(toIndentedString(rekkefolgenummer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
