/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.SprakFelter;

/**
 * TilbudsStatusInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class TilbudsStatusInfo {

  @JsonProperty("kode")

  private String kode = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("prioritet")

  private Integer prioritet = null;

  @JsonProperty("felles")

  private Boolean felles = null;

  @JsonProperty("nasjonalOpptaksmodell")

  private Boolean nasjonalOpptaksmodell = null;

  @JsonProperty("onskerTilbud")

  private Boolean onskerTilbud = null;

  @JsonProperty("tarPlass")

  private Boolean tarPlass = null;

  @JsonProperty("girTilbud")

  private Boolean girTilbud = null;
  public TilbudsStatusInfo kode(String kode) {
    this.kode = kode;
    return this;
  }

  

  /**
  * Get kode
  * @return kode
  **/
  @Schema(description = "")
  public String getKode() {
    return kode;
  }
  public void setKode(String kode) {
    this.kode = kode;
  }
  public TilbudsStatusInfo navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public TilbudsStatusInfo prioritet(Integer prioritet) {
    this.prioritet = prioritet;
    return this;
  }

  

  /**
  * Get prioritet
  * @return prioritet
  **/
  @Schema(description = "")
  public Integer getPrioritet() {
    return prioritet;
  }
  public void setPrioritet(Integer prioritet) {
    this.prioritet = prioritet;
  }
  public TilbudsStatusInfo felles(Boolean felles) {
    this.felles = felles;
    return this;
  }

  

  /**
  * Get felles
  * @return felles
  **/
  @Schema(description = "")
  public Boolean isFelles() {
    return felles;
  }
  public void setFelles(Boolean felles) {
    this.felles = felles;
  }
  public TilbudsStatusInfo nasjonalOpptaksmodell(Boolean nasjonalOpptaksmodell) {
    this.nasjonalOpptaksmodell = nasjonalOpptaksmodell;
    return this;
  }

  

  /**
  * Get nasjonalOpptaksmodell
  * @return nasjonalOpptaksmodell
  **/
  @Schema(description = "")
  public Boolean isNasjonalOpptaksmodell() {
    return nasjonalOpptaksmodell;
  }
  public void setNasjonalOpptaksmodell(Boolean nasjonalOpptaksmodell) {
    this.nasjonalOpptaksmodell = nasjonalOpptaksmodell;
  }
  public TilbudsStatusInfo onskerTilbud(Boolean onskerTilbud) {
    this.onskerTilbud = onskerTilbud;
    return this;
  }

  

  /**
  * Get onskerTilbud
  * @return onskerTilbud
  **/
  @Schema(description = "")
  public Boolean isOnskerTilbud() {
    return onskerTilbud;
  }
  public void setOnskerTilbud(Boolean onskerTilbud) {
    this.onskerTilbud = onskerTilbud;
  }
  public TilbudsStatusInfo tarPlass(Boolean tarPlass) {
    this.tarPlass = tarPlass;
    return this;
  }

  

  /**
  * Get tarPlass
  * @return tarPlass
  **/
  @Schema(description = "")
  public Boolean isTarPlass() {
    return tarPlass;
  }
  public void setTarPlass(Boolean tarPlass) {
    this.tarPlass = tarPlass;
  }
  public TilbudsStatusInfo girTilbud(Boolean girTilbud) {
    this.girTilbud = girTilbud;
    return this;
  }

  

  /**
  * Get girTilbud
  * @return girTilbud
  **/
  @Schema(description = "")
  public Boolean isGirTilbud() {
    return girTilbud;
  }
  public void setGirTilbud(Boolean girTilbud) {
    this.girTilbud = girTilbud;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TilbudsStatusInfo tilbudsStatusInfo = (TilbudsStatusInfo) o;
    return Objects.equals(this.kode, tilbudsStatusInfo.kode) &&
        Objects.equals(this.navn, tilbudsStatusInfo.navn) &&
        Objects.equals(this.prioritet, tilbudsStatusInfo.prioritet) &&
        Objects.equals(this.felles, tilbudsStatusInfo.felles) &&
        Objects.equals(this.nasjonalOpptaksmodell, tilbudsStatusInfo.nasjonalOpptaksmodell) &&
        Objects.equals(this.onskerTilbud, tilbudsStatusInfo.onskerTilbud) &&
        Objects.equals(this.tarPlass, tilbudsStatusInfo.tarPlass) &&
        Objects.equals(this.girTilbud, tilbudsStatusInfo.girTilbud);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(kode, navn, prioritet, felles, nasjonalOpptaksmodell, onskerTilbud, tarPlass, girTilbud);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TilbudsStatusInfo {\n");
    
    sb.append("    kode: ").append(toIndentedString(kode)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    prioritet: ").append(toIndentedString(prioritet)).append("\n");
    sb.append("    felles: ").append(toIndentedString(felles)).append("\n");
    sb.append("    nasjonalOpptaksmodell: ").append(toIndentedString(nasjonalOpptaksmodell)).append("\n");
    sb.append("    onskerTilbud: ").append(toIndentedString(onskerTilbud)).append("\n");
    sb.append("    tarPlass: ").append(toIndentedString(tarPlass)).append("\n");
    sb.append("    girTilbud: ").append(toIndentedString(girTilbud)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
