/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.DatoIntervaller;
import no.bibsys.fs.model.Id2;
import no.bibsys.fs.model.LmsInfo;
import no.bibsys.fs.model.UndervisningsenhetId;
import org.threeten.bp.LocalDate;

/**
 * Undervisningsenhet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Undervisningsenhet {

  @JsonProperty("id")

  private UndervisningsenhetId id = null;

  @JsonProperty("lukket")

  private Boolean lukket = null;

  @JsonProperty("antallTilbud")

  private Integer antallTilbud = null;

  @JsonProperty("perioder")

  private DatoIntervaller perioder = null;

  @JsonProperty("svarfrist")

  private LocalDate svarfrist = null;

  @JsonProperty("trekkfrist")

  private LocalDate trekkfrist = null;

  @JsonProperty("lms")

  private LmsInfo lms = null;

  @JsonProperty("emne")

  private Id2 emne = null;
  public Undervisningsenhet id(UndervisningsenhetId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public UndervisningsenhetId getId() {
    return id;
  }
  public void setId(UndervisningsenhetId id) {
    this.id = id;
  }
  public Undervisningsenhet lukket(Boolean lukket) {
    this.lukket = lukket;
    return this;
  }

  

  /**
  * Get lukket
  * @return lukket
  **/
  @Schema(description = "")
  public Boolean isLukket() {
    return lukket;
  }
  public void setLukket(Boolean lukket) {
    this.lukket = lukket;
  }
  public Undervisningsenhet antallTilbud(Integer antallTilbud) {
    this.antallTilbud = antallTilbud;
    return this;
  }

  

  /**
  * Get antallTilbud
  * @return antallTilbud
  **/
  @Schema(description = "")
  public Integer getAntallTilbud() {
    return antallTilbud;
  }
  public void setAntallTilbud(Integer antallTilbud) {
    this.antallTilbud = antallTilbud;
  }
  public Undervisningsenhet perioder(DatoIntervaller perioder) {
    this.perioder = perioder;
    return this;
  }

  

  /**
  * Get perioder
  * @return perioder
  **/
  @Schema(description = "")
  public DatoIntervaller getPerioder() {
    return perioder;
  }
  public void setPerioder(DatoIntervaller perioder) {
    this.perioder = perioder;
  }
  public Undervisningsenhet svarfrist(LocalDate svarfrist) {
    this.svarfrist = svarfrist;
    return this;
  }

  

  /**
  * Get svarfrist
  * @return svarfrist
  **/
  @Schema(description = "")
  public LocalDate getSvarfrist() {
    return svarfrist;
  }
  public void setSvarfrist(LocalDate svarfrist) {
    this.svarfrist = svarfrist;
  }
  public Undervisningsenhet trekkfrist(LocalDate trekkfrist) {
    this.trekkfrist = trekkfrist;
    return this;
  }

  

  /**
  * Get trekkfrist
  * @return trekkfrist
  **/
  @Schema(description = "")
  public LocalDate getTrekkfrist() {
    return trekkfrist;
  }
  public void setTrekkfrist(LocalDate trekkfrist) {
    this.trekkfrist = trekkfrist;
  }
  public Undervisningsenhet lms(LmsInfo lms) {
    this.lms = lms;
    return this;
  }

  

  /**
  * Get lms
  * @return lms
  **/
  @Schema(description = "")
  public LmsInfo getLms() {
    return lms;
  }
  public void setLms(LmsInfo lms) {
    this.lms = lms;
  }
  public Undervisningsenhet emne(Id2 emne) {
    this.emne = emne;
    return this;
  }

  

  /**
  * Get emne
  * @return emne
  **/
  @Schema(description = "")
  public Id2 getEmne() {
    return emne;
  }
  public void setEmne(Id2 emne) {
    this.emne = emne;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Undervisningsenhet undervisningsenhet = (Undervisningsenhet) o;
    return Objects.equals(this.id, undervisningsenhet.id) &&
        Objects.equals(this.lukket, undervisningsenhet.lukket) &&
        Objects.equals(this.antallTilbud, undervisningsenhet.antallTilbud) &&
        Objects.equals(this.perioder, undervisningsenhet.perioder) &&
        Objects.equals(this.svarfrist, undervisningsenhet.svarfrist) &&
        Objects.equals(this.trekkfrist, undervisningsenhet.trekkfrist) &&
        Objects.equals(this.lms, undervisningsenhet.lms) &&
        Objects.equals(this.emne, undervisningsenhet.emne);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, lukket, antallTilbud, perioder, svarfrist, trekkfrist, lms, emne);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Undervisningsenhet {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lukket: ").append(toIndentedString(lukket)).append("\n");
    sb.append("    antallTilbud: ").append(toIndentedString(antallTilbud)).append("\n");
    sb.append("    perioder: ").append(toIndentedString(perioder)).append("\n");
    sb.append("    svarfrist: ").append(toIndentedString(svarfrist)).append("\n");
    sb.append("    trekkfrist: ").append(toIndentedString(trekkfrist)).append("\n");
    sb.append("    lms: ").append(toIndentedString(lms)).append("\n");
    sb.append("    emne: ").append(toIndentedString(emne)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
