/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.DatoIntervaller;
import no.bibsys.fs.model.Id2;
import no.bibsys.fs.model.LmsInfo;
import no.bibsys.fs.model.SprakFelter;
import no.bibsys.fs.model.UndervisningsaktivitetId;
import org.threeten.bp.LocalDate;

/**
 * Undervisningsaktivitet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class Undervisningsaktivitet {

  @JsonProperty("id")

  private UndervisningsaktivitetId id = null;

  @JsonProperty("eier")

  private Id2 eier = null;

  @JsonProperty("parti")

  private Integer parti = null;

  @JsonProperty("form")

  private String form = null;

  @JsonProperty("disiplin")

  private String disiplin = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("nummer")

  private Integer nummer = null;

  @JsonProperty("kanOnskes")

  private Boolean kanOnskes = null;

  @JsonProperty("apentHvisHoySokning")

  private Boolean apentHvisHoySokning = null;

  @JsonProperty("pameldingSlutt")

  private LocalDate pameldingSlutt = null;

  @JsonProperty("perioder")

  private DatoIntervaller perioder = null;

  @JsonProperty("publiseres")

  private Boolean publiseres = null;

  @JsonProperty("publiserPlass")

  private Boolean publiserPlass = null;

  @JsonProperty("avtale")

  private Boolean avtale = null;

  @JsonProperty("eksporterTimeplan")

  private Boolean eksporterTimeplan = null;

  @JsonProperty("lms")

  private LmsInfo lms = null;

  @JsonProperty("kapasitet")

  private Integer kapasitet = null;

  @JsonProperty("antallOnsket")

  private Integer antallOnsket = null;

  @JsonProperty("romtypeOnsket")

  private String romtypeOnsket = null;

  @JsonProperty("campus")

  private String campus = null;

  @JsonProperty("lukket")

  private Boolean lukket = null;

  @JsonProperty("fellesaktivitet")

  private Boolean fellesaktivitet = null;
  public Undervisningsaktivitet id(UndervisningsaktivitetId id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public UndervisningsaktivitetId getId() {
    return id;
  }
  public void setId(UndervisningsaktivitetId id) {
    this.id = id;
  }
  public Undervisningsaktivitet eier(Id2 eier) {
    this.eier = eier;
    return this;
  }

  

  /**
  * Get eier
  * @return eier
  **/
  @Schema(description = "")
  public Id2 getEier() {
    return eier;
  }
  public void setEier(Id2 eier) {
    this.eier = eier;
  }
  public Undervisningsaktivitet parti(Integer parti) {
    this.parti = parti;
    return this;
  }

  

  /**
  * Get parti
  * @return parti
  **/
  @Schema(description = "")
  public Integer getParti() {
    return parti;
  }
  public void setParti(Integer parti) {
    this.parti = parti;
  }
  public Undervisningsaktivitet form(String form) {
    this.form = form;
    return this;
  }

  

  /**
  * Get form
  * @return form
  **/
  @Schema(description = "")
  public String getForm() {
    return form;
  }
  public void setForm(String form) {
    this.form = form;
  }
  public Undervisningsaktivitet disiplin(String disiplin) {
    this.disiplin = disiplin;
    return this;
  }

  

  /**
  * Get disiplin
  * @return disiplin
  **/
  @Schema(description = "")
  public String getDisiplin() {
    return disiplin;
  }
  public void setDisiplin(String disiplin) {
    this.disiplin = disiplin;
  }
  public Undervisningsaktivitet navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public Undervisningsaktivitet nummer(Integer nummer) {
    this.nummer = nummer;
    return this;
  }

  

  /**
  * Get nummer
  * @return nummer
  **/
  @Schema(description = "")
  public Integer getNummer() {
    return nummer;
  }
  public void setNummer(Integer nummer) {
    this.nummer = nummer;
  }
  public Undervisningsaktivitet kanOnskes(Boolean kanOnskes) {
    this.kanOnskes = kanOnskes;
    return this;
  }

  

  /**
  * Get kanOnskes
  * @return kanOnskes
  **/
  @Schema(description = "")
  public Boolean isKanOnskes() {
    return kanOnskes;
  }
  public void setKanOnskes(Boolean kanOnskes) {
    this.kanOnskes = kanOnskes;
  }
  public Undervisningsaktivitet apentHvisHoySokning(Boolean apentHvisHoySokning) {
    this.apentHvisHoySokning = apentHvisHoySokning;
    return this;
  }

  

  /**
  * Get apentHvisHoySokning
  * @return apentHvisHoySokning
  **/
  @Schema(description = "")
  public Boolean isApentHvisHoySokning() {
    return apentHvisHoySokning;
  }
  public void setApentHvisHoySokning(Boolean apentHvisHoySokning) {
    this.apentHvisHoySokning = apentHvisHoySokning;
  }
  public Undervisningsaktivitet pameldingSlutt(LocalDate pameldingSlutt) {
    this.pameldingSlutt = pameldingSlutt;
    return this;
  }

  

  /**
  * Get pameldingSlutt
  * @return pameldingSlutt
  **/
  @Schema(description = "")
  public LocalDate getPameldingSlutt() {
    return pameldingSlutt;
  }
  public void setPameldingSlutt(LocalDate pameldingSlutt) {
    this.pameldingSlutt = pameldingSlutt;
  }
  public Undervisningsaktivitet perioder(DatoIntervaller perioder) {
    this.perioder = perioder;
    return this;
  }

  

  /**
  * Get perioder
  * @return perioder
  **/
  @Schema(description = "")
  public DatoIntervaller getPerioder() {
    return perioder;
  }
  public void setPerioder(DatoIntervaller perioder) {
    this.perioder = perioder;
  }
  public Undervisningsaktivitet publiseres(Boolean publiseres) {
    this.publiseres = publiseres;
    return this;
  }

  

  /**
  * Get publiseres
  * @return publiseres
  **/
  @Schema(description = "")
  public Boolean isPubliseres() {
    return publiseres;
  }
  public void setPubliseres(Boolean publiseres) {
    this.publiseres = publiseres;
  }
  public Undervisningsaktivitet publiserPlass(Boolean publiserPlass) {
    this.publiserPlass = publiserPlass;
    return this;
  }

  

  /**
  * Get publiserPlass
  * @return publiserPlass
  **/
  @Schema(description = "")
  public Boolean isPubliserPlass() {
    return publiserPlass;
  }
  public void setPubliserPlass(Boolean publiserPlass) {
    this.publiserPlass = publiserPlass;
  }
  public Undervisningsaktivitet avtale(Boolean avtale) {
    this.avtale = avtale;
    return this;
  }

  

  /**
  * Get avtale
  * @return avtale
  **/
  @Schema(description = "")
  public Boolean isAvtale() {
    return avtale;
  }
  public void setAvtale(Boolean avtale) {
    this.avtale = avtale;
  }
  public Undervisningsaktivitet eksporterTimeplan(Boolean eksporterTimeplan) {
    this.eksporterTimeplan = eksporterTimeplan;
    return this;
  }

  

  /**
  * Get eksporterTimeplan
  * @return eksporterTimeplan
  **/
  @Schema(description = "")
  public Boolean isEksporterTimeplan() {
    return eksporterTimeplan;
  }
  public void setEksporterTimeplan(Boolean eksporterTimeplan) {
    this.eksporterTimeplan = eksporterTimeplan;
  }
  public Undervisningsaktivitet lms(LmsInfo lms) {
    this.lms = lms;
    return this;
  }

  

  /**
  * Get lms
  * @return lms
  **/
  @Schema(description = "")
  public LmsInfo getLms() {
    return lms;
  }
  public void setLms(LmsInfo lms) {
    this.lms = lms;
  }
  public Undervisningsaktivitet kapasitet(Integer kapasitet) {
    this.kapasitet = kapasitet;
    return this;
  }

  

  /**
  * Get kapasitet
  * @return kapasitet
  **/
  @Schema(description = "")
  public Integer getKapasitet() {
    return kapasitet;
  }
  public void setKapasitet(Integer kapasitet) {
    this.kapasitet = kapasitet;
  }
  public Undervisningsaktivitet antallOnsket(Integer antallOnsket) {
    this.antallOnsket = antallOnsket;
    return this;
  }

  

  /**
  * Get antallOnsket
  * @return antallOnsket
  **/
  @Schema(description = "")
  public Integer getAntallOnsket() {
    return antallOnsket;
  }
  public void setAntallOnsket(Integer antallOnsket) {
    this.antallOnsket = antallOnsket;
  }
  public Undervisningsaktivitet romtypeOnsket(String romtypeOnsket) {
    this.romtypeOnsket = romtypeOnsket;
    return this;
  }

  

  /**
  * Get romtypeOnsket
  * @return romtypeOnsket
  **/
  @Schema(description = "")
  public String getRomtypeOnsket() {
    return romtypeOnsket;
  }
  public void setRomtypeOnsket(String romtypeOnsket) {
    this.romtypeOnsket = romtypeOnsket;
  }
  public Undervisningsaktivitet campus(String campus) {
    this.campus = campus;
    return this;
  }

  

  /**
  * Get campus
  * @return campus
  **/
  @Schema(description = "")
  public String getCampus() {
    return campus;
  }
  public void setCampus(String campus) {
    this.campus = campus;
  }
  public Undervisningsaktivitet lukket(Boolean lukket) {
    this.lukket = lukket;
    return this;
  }

  

  /**
  * Get lukket
  * @return lukket
  **/
  @Schema(description = "")
  public Boolean isLukket() {
    return lukket;
  }
  public void setLukket(Boolean lukket) {
    this.lukket = lukket;
  }
  public Undervisningsaktivitet fellesaktivitet(Boolean fellesaktivitet) {
    this.fellesaktivitet = fellesaktivitet;
    return this;
  }

  

  /**
  * Get fellesaktivitet
  * @return fellesaktivitet
  **/
  @Schema(description = "")
  public Boolean isFellesaktivitet() {
    return fellesaktivitet;
  }
  public void setFellesaktivitet(Boolean fellesaktivitet) {
    this.fellesaktivitet = fellesaktivitet;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Undervisningsaktivitet undervisningsaktivitet = (Undervisningsaktivitet) o;
    return Objects.equals(this.id, undervisningsaktivitet.id) &&
        Objects.equals(this.eier, undervisningsaktivitet.eier) &&
        Objects.equals(this.parti, undervisningsaktivitet.parti) &&
        Objects.equals(this.form, undervisningsaktivitet.form) &&
        Objects.equals(this.disiplin, undervisningsaktivitet.disiplin) &&
        Objects.equals(this.navn, undervisningsaktivitet.navn) &&
        Objects.equals(this.nummer, undervisningsaktivitet.nummer) &&
        Objects.equals(this.kanOnskes, undervisningsaktivitet.kanOnskes) &&
        Objects.equals(this.apentHvisHoySokning, undervisningsaktivitet.apentHvisHoySokning) &&
        Objects.equals(this.pameldingSlutt, undervisningsaktivitet.pameldingSlutt) &&
        Objects.equals(this.perioder, undervisningsaktivitet.perioder) &&
        Objects.equals(this.publiseres, undervisningsaktivitet.publiseres) &&
        Objects.equals(this.publiserPlass, undervisningsaktivitet.publiserPlass) &&
        Objects.equals(this.avtale, undervisningsaktivitet.avtale) &&
        Objects.equals(this.eksporterTimeplan, undervisningsaktivitet.eksporterTimeplan) &&
        Objects.equals(this.lms, undervisningsaktivitet.lms) &&
        Objects.equals(this.kapasitet, undervisningsaktivitet.kapasitet) &&
        Objects.equals(this.antallOnsket, undervisningsaktivitet.antallOnsket) &&
        Objects.equals(this.romtypeOnsket, undervisningsaktivitet.romtypeOnsket) &&
        Objects.equals(this.campus, undervisningsaktivitet.campus) &&
        Objects.equals(this.lukket, undervisningsaktivitet.lukket) &&
        Objects.equals(this.fellesaktivitet, undervisningsaktivitet.fellesaktivitet);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, eier, parti, form, disiplin, navn, nummer, kanOnskes, apentHvisHoySokning, pameldingSlutt, perioder, publiseres, publiserPlass, avtale, eksporterTimeplan, lms, kapasitet, antallOnsket, romtypeOnsket, campus, lukket, fellesaktivitet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Undervisningsaktivitet {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    eier: ").append(toIndentedString(eier)).append("\n");
    sb.append("    parti: ").append(toIndentedString(parti)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    disiplin: ").append(toIndentedString(disiplin)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    nummer: ").append(toIndentedString(nummer)).append("\n");
    sb.append("    kanOnskes: ").append(toIndentedString(kanOnskes)).append("\n");
    sb.append("    apentHvisHoySokning: ").append(toIndentedString(apentHvisHoySokning)).append("\n");
    sb.append("    pameldingSlutt: ").append(toIndentedString(pameldingSlutt)).append("\n");
    sb.append("    perioder: ").append(toIndentedString(perioder)).append("\n");
    sb.append("    publiseres: ").append(toIndentedString(publiseres)).append("\n");
    sb.append("    publiserPlass: ").append(toIndentedString(publiserPlass)).append("\n");
    sb.append("    avtale: ").append(toIndentedString(avtale)).append("\n");
    sb.append("    eksporterTimeplan: ").append(toIndentedString(eksporterTimeplan)).append("\n");
    sb.append("    lms: ").append(toIndentedString(lms)).append("\n");
    sb.append("    kapasitet: ").append(toIndentedString(kapasitet)).append("\n");
    sb.append("    antallOnsket: ").append(toIndentedString(antallOnsket)).append("\n");
    sb.append("    romtypeOnsket: ").append(toIndentedString(romtypeOnsket)).append("\n");
    sb.append("    campus: ").append(toIndentedString(campus)).append("\n");
    sb.append("    lukket: ").append(toIndentedString(lukket)).append("\n");
    sb.append("    fellesaktivitet: ").append(toIndentedString(fellesaktivitet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
