/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.Id2;

/**
 * UndervisningsenhetId
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class UndervisningsenhetId {

  @JsonProperty("href")

  private String href = null;
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    FELLESUNDERVISNING("FELLESUNDERVISNING");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }
  @JsonProperty("type")

  private TypeEnum type = null;

  @JsonProperty("emne")

  private Id2 emne = null;

  @JsonProperty("semester")

  private Id2 semester = null;

  @JsonProperty("terminnummer")

  private Integer terminnummer = null;
  public UndervisningsenhetId href(String href) {
    this.href = href;
    return this;
  }

  

  /**
  * Get href
  * @return href
  **/
  @Schema(example = "https://server/undervisning/id", description = "")
  public String getHref() {
    return href;
  }
  public void setHref(String href) {
    this.href = href;
  }
  public UndervisningsenhetId type(TypeEnum type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }
  public void setType(TypeEnum type) {
    this.type = type;
  }
  public UndervisningsenhetId emne(Id2 emne) {
    this.emne = emne;
    return this;
  }

  

  /**
  * Get emne
  * @return emne
  **/
  @Schema(description = "")
  public Id2 getEmne() {
    return emne;
  }
  public void setEmne(Id2 emne) {
    this.emne = emne;
  }
  public UndervisningsenhetId semester(Id2 semester) {
    this.semester = semester;
    return this;
  }

  

  /**
  * Get semester
  * @return semester
  **/
  @Schema(description = "")
  public Id2 getSemester() {
    return semester;
  }
  public void setSemester(Id2 semester) {
    this.semester = semester;
  }
  public UndervisningsenhetId terminnummer(Integer terminnummer) {
    this.terminnummer = terminnummer;
    return this;
  }

  

  /**
  * Get terminnummer
  * @return terminnummer
  **/
  @Schema(description = "")
  public Integer getTerminnummer() {
    return terminnummer;
  }
  public void setTerminnummer(Integer terminnummer) {
    this.terminnummer = terminnummer;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UndervisningsenhetId undervisningsenhetId = (UndervisningsenhetId) o;
    return Objects.equals(this.href, undervisningsenhetId.href) &&
        Objects.equals(this.type, undervisningsenhetId.type) &&
        Objects.equals(this.emne, undervisningsenhetId.emne) &&
        Objects.equals(this.semester, undervisningsenhetId.semester) &&
        Objects.equals(this.terminnummer, undervisningsenhetId.terminnummer);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(href, type, emne, semester, terminnummer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UndervisningsenhetId {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    emne: ").append(toIndentedString(emne)).append("\n");
    sb.append("    semester: ").append(toIndentedString(semester)).append("\n");
    sb.append("    terminnummer: ").append(toIndentedString(terminnummer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
