/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import no.bibsys.fs.model.TidsenhetInfo;

/**
 * VarighetInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class VarighetInfo {

  @JsonProperty("verdi")

  private BigDecimal verdi = null;

  @JsonProperty("tidsenhet")

  private TidsenhetInfo tidsenhet = null;
  public VarighetInfo verdi(BigDecimal verdi) {
    this.verdi = verdi;
    return this;
  }

  

  /**
  * Get verdi
  * @return verdi
  **/
  @Schema(description = "")
  public BigDecimal getVerdi() {
    return verdi;
  }
  public void setVerdi(BigDecimal verdi) {
    this.verdi = verdi;
  }
  public VarighetInfo tidsenhet(TidsenhetInfo tidsenhet) {
    this.tidsenhet = tidsenhet;
    return this;
  }

  

  /**
  * Get tidsenhet
  * @return tidsenhet
  **/
  @Schema(description = "")
  public TidsenhetInfo getTidsenhet() {
    return tidsenhet;
  }
  public void setTidsenhet(TidsenhetInfo tidsenhet) {
    this.tidsenhet = tidsenhet;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VarighetInfo varighetInfo = (VarighetInfo) o;
    return Objects.equals(this.verdi, varighetInfo.verdi) &&
        Objects.equals(this.tidsenhet, varighetInfo.tidsenhet);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(verdi, tidsenhet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VarighetInfo {\n");
    
    sb.append("    verdi: ").append(toIndentedString(verdi)).append("\n");
    sb.append("    tidsenhet: ").append(toIndentedString(tidsenhet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
