/*
 * FS-API
 * FS-API'et er et generelt grensesnitt mot Felles Studentsystem (FS)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.bibsys.fs.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import no.bibsys.fs.model.SprakFelter;

/**
 * VitenskapsDisiplinInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-04-25T14:26:52.663+02:00[Europe/Paris]")public class VitenskapsDisiplinInfo {

  @JsonProperty("kode")

  private String kode = null;

  @JsonProperty("navn")

  private SprakFelter navn = null;

  @JsonProperty("niva")

  private Integer niva = null;

  @JsonProperty("eierdisiplin")

  private String eierdisiplin = null;

  @JsonProperty("felles")

  private Boolean felles = null;
  public VitenskapsDisiplinInfo kode(String kode) {
    this.kode = kode;
    return this;
  }

  

  /**
  * Get kode
  * @return kode
  **/
  @Schema(description = "")
  public String getKode() {
    return kode;
  }
  public void setKode(String kode) {
    this.kode = kode;
  }
  public VitenskapsDisiplinInfo navn(SprakFelter navn) {
    this.navn = navn;
    return this;
  }

  

  /**
  * Get navn
  * @return navn
  **/
  @Schema(description = "")
  public SprakFelter getNavn() {
    return navn;
  }
  public void setNavn(SprakFelter navn) {
    this.navn = navn;
  }
  public VitenskapsDisiplinInfo niva(Integer niva) {
    this.niva = niva;
    return this;
  }

  

  /**
  * Get niva
  * @return niva
  **/
  @Schema(description = "")
  public Integer getNiva() {
    return niva;
  }
  public void setNiva(Integer niva) {
    this.niva = niva;
  }
  public VitenskapsDisiplinInfo eierdisiplin(String eierdisiplin) {
    this.eierdisiplin = eierdisiplin;
    return this;
  }

  

  /**
  * Get eierdisiplin
  * @return eierdisiplin
  **/
  @Schema(description = "")
  public String getEierdisiplin() {
    return eierdisiplin;
  }
  public void setEierdisiplin(String eierdisiplin) {
    this.eierdisiplin = eierdisiplin;
  }
  public VitenskapsDisiplinInfo felles(Boolean felles) {
    this.felles = felles;
    return this;
  }

  

  /**
  * Get felles
  * @return felles
  **/
  @Schema(description = "")
  public Boolean isFelles() {
    return felles;
  }
  public void setFelles(Boolean felles) {
    this.felles = felles;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VitenskapsDisiplinInfo vitenskapsDisiplinInfo = (VitenskapsDisiplinInfo) o;
    return Objects.equals(this.kode, vitenskapsDisiplinInfo.kode) &&
        Objects.equals(this.navn, vitenskapsDisiplinInfo.navn) &&
        Objects.equals(this.niva, vitenskapsDisiplinInfo.niva) &&
        Objects.equals(this.eierdisiplin, vitenskapsDisiplinInfo.eierdisiplin) &&
        Objects.equals(this.felles, vitenskapsDisiplinInfo.felles);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(kode, navn, niva, eierdisiplin, felles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VitenskapsDisiplinInfo {\n");
    
    sb.append("    kode: ").append(toIndentedString(kode)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    niva: ").append(toIndentedString(niva)).append("\n");
    sb.append("    eierdisiplin: ").append(toIndentedString(eierdisiplin)).append("\n");
    sb.append("    felles: ").append(toIndentedString(felles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
